import{obtenirDocApiGrist,TableGrist}from"./grist-context.js";import{UtilisateurCourant}from"./portal-data.js";
export interface EvenementAudit{id:number;acteur:string;typeObjet:string;objetUid:string;action:string;resume:string;perimetre:string;date:string;timestamp:number;}export interface DonneesAudit{evenements:readonly EvenementAudit[];}
export const EXPORTS_AUTORISES=[{id:"Utilisateurs",libelle:"Utilisateurs et rôles",description:"Comptes, rôles, statuts et rattachements accessibles."},{id:"Evaluations",libelle:"Évaluations",description:"Campagnes, statuts et dates des évaluations accessibles."},{id:"ActionsProgres",libelle:"Actions de progrès",description:"Actions, échéances et états de validation accessibles."},{id:"JournalAudit",libelle:"Journal d’audit",description:"Traçabilité des opérations sensibles."}]as const;
export async function chargerAudit():Promise<DonneesAudit>{const api=obtenirDocApiGrist();if(!api)return{evenements:construireAudit(demoAudit(),demoPerimetres())};const[a,p]=await Promise.all([api.fetchTable("JournalAudit"),api.fetchTable("Perimetres")]);return{evenements:construireAudit(a,p)};}
export function construireAudit(table:TableGrist,perimetres:TableGrist):EvenementAudit[]{const noms=new Map<number,string>();(perimetres.id??[]).forEach((v,i)=>{if(typeof v==="number")noms.set(v,texte(perimetres.Nom?.[i])||`Périmètre ${v}`);});return(table.id??[]).flatMap((v,i)=>{if(typeof v!=="number")return[];const p=referenceId(table.Perimetre?.[i]),ts=nombre(table.DateEvenement?.[i])??0;return[{id:v,acteur:texte(table.ActeurEmail?.[i])||"—",typeObjet:texte(table.TypeObjet?.[i]),objetUid:texte(table.ObjetUid?.[i]),action:texte(table.Action?.[i]),resume:texte(table.Resume?.[i]),perimetre:p?(noms.get(p)||`Périmètre ${p}`):"Global",date:dateHeure(ts),timestamp:ts}];}).sort((a,b)=>b.timestamp-a.timestamp);}
export async function exporterTable(tableId:string,u:UtilisateurCourant):Promise<{nom:string;contenu:string}>{const api=obtenirDocApiGrist();if(!api)throw new Error("Les exports sont disponibles uniquement depuis le widget Grist.");if(!EXPORTS_AUTORISES.some(x=>x.id===tableId))throw new Error("Cet export n’est pas autorisé.");const table=await api.fetchTable(tableId);const contenu=tableVersCsv(table);await api.applyUserActions([["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:u.id,TypeObjet:"EXPORT",ObjetUid:tableId,Action:"EXPORT_CSV",Resume:`Export CSV ${tableId}`}]]);return{nom:`ensosp-${tableId.toLocaleLowerCase("fr")}-${new Date().toISOString().slice(0,10)}.csv`,contenu};}
export function telechargerCsv(nom:string,contenu:string):void{const blob=new Blob(["\uFEFF",contenu],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),lien=document.createElement("a");lien.href=url;lien.download=nom;lien.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
export function tableVersCsv(table:TableGrist):string{const colonnes=Object.keys(table),lignes=Math.max(0,...colonnes.map(c=>table[c]?.length??0));const echapper=(v:unknown)=>{const s=cellule(v);return/[;"\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};return[colonnes.join(";"),...Array.from({length:lignes},(_,i)=>colonnes.map(c=>echapper(table[c]?.[i])).join(";"))].join("\r\n");}
function cellule(v:unknown):string{if(v==null)return"";if(Array.isArray(v))return v.filter(x=>x!=="L").join(", ");if(typeof v==="object")return JSON.stringify(v);return String(v);}function demoAudit():TableGrist{return{id:[1,2,3],ActeurEmail:["admin@example.invalid","admin@example.invalid","superviseur@example.invalid"],TypeObjet:["PARAMETRE","FICHE","VALIDATION"],ObjetUid:["PDF_MAX_SIZE_MB","FICHE_IND_01","VAL-001"],Action:["MODIFICATION","PUBLICATION","VALIDATION"],Resume:["Paramètre PDF_MAX_SIZE_MB mis à jour","Publication de la fiche FICHE_IND_01","Progrès validé"],Perimetre:[null,null,1],DateEvenement:[1_730_000_000,1_729_900_000,1_729_800_000]};}function demoPerimetres():TableGrist{return{id:[1],Nom:["Périmètre national"]};}function referenceId(v:unknown):number|null{if(typeof v==="number"&&v>0)return v;if(Array.isArray(v)){for(let i=v.length-1;i>=0;i--){if(typeof v[i]==="number"&&(v[i]as number)>0)return v[i]as number;}}return null;}function nombre(v:unknown):number|null{return typeof v==="number"&&Number.isFinite(v)?v:null;}function texte(v:unknown):string{return typeof v==="string"?v:"";}function dateHeure(ts:number):string{return ts?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(ts*1000)):"—";}
