import { obtenirDocApiGrist, TableGrist } from "./grist-context.js";
import { Niveau } from "./evaluation-data.js";
import { UtilisateurCourant } from "./portal-data.js";

export interface ProfilMetier { id:number; nom:string; email:string; role:string; perimetre:string; actif:boolean; dateDeblocageEvaluationTimestamp:number; }
export interface EvaluationMetier { id:number; uid:string; recruteurId:number; recruteur:string; perimetre:string; statut:string; progression:number; dateDebut:string; dateValidation:string; dateValidationTimestamp:number; reponses:readonly ReponseMetier[]; }
export interface ReponseMetier { id:number; evaluationId:number; indicateurId:number; indicateur:string; codeIndicateur:string; niveau:Niveau; commentaire:string; }
export interface ActionMetier { id:number; uid:string; recruteurId:number; recruteur:string; perimetreId:number|null; perimetre:string; indicateur:string; codeIndicateur:string; niveauInitial:Niveau; niveauCourant:Niveau; statut:string; echeance:string; echeanceTimestamp:number; commentaireRecruteur:string; commentaireSuperviseur:string; priseEnCompteFiche:boolean; ficheVersionId:number|null; fiche:string; version:string; nomFichier:string; attachmentId:number|null; }
export interface FicheDisponible { id:number; versionId:number; code:string; titre:string; description:string; indicateurId:number; indicateur:string; codeIndicateur:string; niveau:Niveau; version:string; nomFichier:string; attachmentId:number; }
export interface ValidationMetier { id:number; actionId:number; recruteur:string; superviseur:string; decision:string; ancienNiveau:Niveau; nouveauNiveau:Niveau|null; commentaire:string; date:string; }
export interface DonneesOperationnelles { profils:readonly ProfilMetier[]; evaluations:readonly EvaluationMetier[]; actions:readonly ActionMetier[]; validations:readonly ValidationMetier[]; fiches:readonly FicheDisponible[]; }
export type DecisionValidation="VALIDEE"|"COMPLEMENT_DEMANDE"|"REFUSEE";

export function peutConsulterFiches(evaluations:readonly EvaluationMetier[],utilisateurId:number):boolean{return evaluations.some(e=>e.recruteurId===utilisateurId&&e.statut==="VALIDEE"&&e.progression===100);}

const TABLES=["Utilisateurs","Perimetres","Evaluations","Reponses","Indicateurs","ActionsProgres","Validations","FicheVersions","FichesEnseignement","FicheIndicateurs"] as const;

export async function chargerDonneesOperationnelles():Promise<DonneesOperationnelles>{
  const api=obtenirDocApiGrist();
  if(!api)return construireDonneesOperationnelles(...demoTables());
  const [utilisateurs,perimetres,evaluations,reponses,indicateurs,actions,validations,versions,fiches,liaisons]=await Promise.all([
    api.fetchTable(TABLES[0]),api.fetchTable(TABLES[1]),api.fetchTable(TABLES[2]),api.fetchTable(TABLES[3]),api.fetchTable(TABLES[4]),api.fetchTable(TABLES[5]),api.fetchTable(TABLES[6]),api.fetchTable(TABLES[7]),api.fetchTable(TABLES[8]),api.fetchTable(TABLES[9]),
  ]);
  return construireDonneesOperationnelles(utilisateurs,perimetres,evaluations,reponses,indicateurs,actions,validations,versions,fiches,liaisons);
}

export function construireDonneesOperationnelles(utilisateurs:TableGrist,perimetres:TableGrist,evaluations:TableGrist,reponses:TableGrist,indicateurs:TableGrist,actions:TableGrist,validations:TableGrist,versions:TableGrist,fiches:TableGrist,liaisons:TableGrist={id:[]}):DonneesOperationnelles{
  const nomsPerimetres=libelles(perimetres,"Nom"), nomsIndicateurs=libelles(indicateurs,"Titre"), codesIndicateurs=libelles(indicateurs,"Code"), nomsFiches=libelles(fiches,"Titre"), codesFiches=libelles(fiches,"Code");
  const profils:ProfilMetier[]=[];const nomsUtilisateurs=new Map<number,string>();
  (utilisateurs.id??[]).forEach((v,i)=>{const id=nombre(v);if(!id)return;const nom=`${texte(utilisateurs.Prenom?.[i])} ${texte(utilisateurs.Nom?.[i])}`.trim()||texte(utilisateurs.Email?.[i]);nomsUtilisateurs.set(id,nom);profils.push({id,nom,email:texte(utilisateurs.Email?.[i]),role:texte(utilisateurs.Role?.[i]),perimetre:nomsPerimetres.get(referenceId(utilisateurs.PerimetrePrincipal?.[i])??0)||"Non renseigné",actif:booleen(utilisateurs.Actif?.[i]),dateDeblocageEvaluationTimestamp:nombre(utilisateurs.DateDeblocageEvaluation?.[i])??0});});
  const reponsesNormalisees:ReponseMetier[]=(reponses.id??[]).flatMap((v,i)=>{const id=nombre(v),evaluationId=referenceId(reponses.Evaluation?.[i]),indicateurId=referenceId(reponses.Indicateur?.[i]),niveau=normaliserNiveau(reponses.Niveau?.[i]);if(!id||!evaluationId||!indicateurId||!niveau)return[];return[{id,evaluationId,indicateurId,indicateur:nomsIndicateurs.get(indicateurId)||`Indicateur ${indicateurId}`,codeIndicateur:codesIndicateurs.get(indicateurId)||"",niveau,commentaire:texte(reponses.CommentaireRecruteur?.[i])}];});
  const evaluationsNormalisees:EvaluationMetier[]=(evaluations.id??[]).flatMap((v,i)=>{const id=nombre(v),recruteurId=referenceId(evaluations.Recruteur?.[i]);if(!id||!recruteurId)return[];const dateValidationTimestamp=nombre(evaluations.DateValidation?.[i])??nombre(evaluations.UpdatedAt?.[i])??0;return[{id,uid:texte(evaluations.Uid?.[i]),recruteurId,recruteur:nomsUtilisateurs.get(recruteurId)||`Utilisateur ${recruteurId}`,perimetre:nomsPerimetres.get(referenceId(evaluations.Perimetre?.[i])??0)||"Non renseigné",statut:texte(evaluations.Statut?.[i]),progression:nombre(evaluations.ProgressionComplete?.[i])??0,dateDebut:dateHeure(evaluations.DateDebut?.[i]),dateValidation:dateHeure(evaluations.DateValidation?.[i]),dateValidationTimestamp,reponses:reponsesNormalisees.filter(r=>r.evaluationId===id)}];}).sort((a,b)=>b.id-a.id);
  const versionInfos=new Map<number,{ficheId:number|null;fiche:string;version:string;nom:string;attachment:number|null;publiee:boolean}>();(versions.id??[]).forEach((v,i)=>{const id=nombre(v),ficheId=referenceId(versions.Fiche?.[i]);if(!id)return;versionInfos.set(id,{ficheId,fiche:(ficheId&&(nomsFiches.get(ficheId)||codesFiches.get(ficheId)))||"Fiche pédagogique",version:texte(versions.NumeroVersion?.[i]),nom:texte(versions.NomFichier?.[i]),attachment:attachmentId(versions.FichierPDF?.[i]),publiee:booleen(versions.EstPubliee?.[i])});});
  const actionsNormalisees:ActionMetier[]=(actions.id??[]).flatMap((v,i)=>{const id=nombre(v),recruteurId=referenceId(actions.Recruteur?.[i]),perimetreId=referenceId(actions.Perimetre?.[i]),indicateurId=referenceId(actions.Indicateur?.[i]),niveauInitial=normaliserNiveau(actions.NiveauInitial?.[i]),niveauCourant=normaliserNiveau(actions.NiveauCourant?.[i]);if(!id||!recruteurId||!niveauInitial||!niveauCourant)return[];const ficheVersionId=referenceId(actions.FicheVersion?.[i]),info=ficheVersionId?versionInfos.get(ficheVersionId):undefined;const echeanceTimestamp=nombre(actions.Echeance?.[i])??0;return[{id,uid:texte(actions.Uid?.[i]),recruteurId,recruteur:nomsUtilisateurs.get(recruteurId)||`Utilisateur ${recruteurId}`,perimetreId,perimetre:nomsPerimetres.get(perimetreId??0)||"Non renseigné",indicateur:nomsIndicateurs.get(indicateurId??0)||`Indicateur ${indicateurId??""}`,codeIndicateur:codesIndicateurs.get(indicateurId??0)||"",niveauInitial,niveauCourant,statut:texte(actions.Statut?.[i]),echeance:dateSeule(echeanceTimestamp),echeanceTimestamp,commentaireRecruteur:texte(actions.CommentaireRecruteur?.[i]),commentaireSuperviseur:texte(actions.CommentaireSuperviseur?.[i]),priseEnCompteFiche:booleen(actions.PriseEnCompteFiche?.[i]),ficheVersionId:ficheVersionId??null,fiche:info?.fiche||"—",version:info?.version||"",nomFichier:info?.nom||"",attachmentId:info?.attachment??null}];}).sort((a,b)=>a.echeanceTimestamp-b.echeanceTimestamp);
  const validationsNormalisees:ValidationMetier[]=(validations.id??[]).flatMap((v,i)=>{const id=nombre(v),actionId=referenceId(validations.ActionProgres?.[i]),ancien=normaliserNiveau(validations.AncienNiveau?.[i]);if(!id||!actionId||!ancien)return[];return[{id,actionId,recruteur:nomsUtilisateurs.get(referenceId(validations.Recruteur?.[i])??0)||"—",superviseur:nomsUtilisateurs.get(referenceId(validations.Superviseur?.[i])??0)||"—",decision:texte(validations.Decision?.[i]),ancienNiveau:ancien,nouveauNiveau:normaliserNiveau(validations.NouveauNiveau?.[i]),commentaire:texte(validations.Commentaire?.[i]),date:dateHeure(validations.DateDecision?.[i])}];}).sort((a,b)=>b.id-a.id);
  const fichesDisponibles:FicheDisponible[]=(fiches.id??[]).flatMap((v,i)=>{const id=nombre(v),versionId=referenceId(fiches.VersionActive?.[i]);if(!id||!versionId||texte(fiches.Statut?.[i])!=="PUBLIEE"||!booleen(fiches.Actif?.[i]))return[];const info=versionInfos.get(versionId);if(!info?.attachment||!info.publiee)return[];const li=(liaisons.id??[]).findIndex((_,x)=>referenceId(liaisons.Fiche?.[x])===id&&booleen(liaisons.Actif?.[x]));const indicateurId=referenceId(liaisons.Indicateur?.[li]);const niveau:Niveau|null=booleen(liaisons.DeclencheRouge?.[li])?"ROUGE":booleen(liaisons.DeclencheOrange?.[li])?"ORANGE":null;if(!indicateurId||!niveau)return[];return[{id,versionId,code:codesFiches.get(id)||"",titre:nomsFiches.get(id)||"Fiche d’enseignement",description:texte(fiches.Description?.[i]),indicateurId,indicateur:nomsIndicateurs.get(indicateurId)||`Indicateur ${indicateurId}`,codeIndicateur:codesIndicateurs.get(indicateurId)||"",niveau,version:info.version,nomFichier:info.nom,attachmentId:info.attachment}];}).sort((a,b)=>a.code.localeCompare(b.code,"fr"));
  return{profils:profils.sort((a,b)=>a.nom.localeCompare(b.nom,"fr")),evaluations:evaluationsNormalisees,actions:actionsNormalisees,validations:validationsNormalisees,fiches:fichesDisponibles};
}

export async function declarerProgression(action:ActionMetier,commentaire:string,utilisateur:UtilisateurCourant,priseEnCompte:boolean):Promise<void>{const api=exigerApi();if(!action.ficheVersionId)throw new Error("Aucune fiche d’enseignement publiée n’est rattachée à cet indicateur.");if(!priseEnCompte)throw new Error("Confirmez la prise en compte de la fiche d’enseignement avant de demander la validation.");const mention="Prise en compte de la fiche d’enseignement réalisée",date=maintenant();await api.applyUserActions([["UpdateRecord","ActionsProgres",action.id,{Statut:"EN_ATTENTE_VALIDATION",CommentaireRecruteur:commentaire.trim()||mention,PriseEnCompteFiche:true,DatePriseEnCompte:date}],["AddRecord","ConsultationsFiches",null,{Uid:crypto.randomUUID(),FicheVersion:action.ficheVersionId,ActionProgres:action.id,Recruteur:utilisateur.id,Perimetre:action.perimetreId,TypeEvenement:"PRISE_EN_COMPTE",DateEvenement:date}]]);}
export async function demarrerAction(actionId:number):Promise<void>{const api=exigerApi();await api.applyUserActions([["UpdateRecord","ActionsProgres",actionId,{Statut:"EN_COURS",DatePriseEnCompte:maintenant()}]]);}
export async function deciderAction(action:ActionMetier,decision:DecisionValidation,nouveau:Niveau|null,commentaire:string,utilisateur:UtilisateurCourant):Promise<void>{const api=exigerApi();if(decision==="VALIDEE"&&!action.priseEnCompteFiche)throw new Error("La prise en compte de la fiche d’enseignement doit être déclarée avant validation.");if(decision==="VALIDEE"&&nouveau!=="VERT")throw new Error("La validation de la fiche entraîne uniquement le passage au vert.");if(decision!=="VALIDEE"&&!commentaire.trim())throw new Error("Un commentaire est obligatoire pour un complément ou un refus.");if(!action.perimetreId)throw new Error("Le périmètre de cette action est introuvable.");const statut=decision==="VALIDEE"?"PROGRESSION_VALIDEE":decision==="COMPLEMENT_DEMANDE"?"COMPLEMENT_DEMANDE":"VALIDATION_REFUSEE";await api.applyUserActions([["AddRecord","Validations",null,{Uid:crypto.randomUUID(),ActionProgres:action.id,Recruteur:action.recruteurId,Perimetre:action.perimetreId,Superviseur:utilisateur.id,Decision:decision,AncienNiveau:action.niveauCourant,NouveauNiveau:nouveau,Commentaire:commentaire.trim()}],["UpdateRecord","ActionsProgres",action.id,{NiveauCourant:nouveau??action.niveauCourant,Statut:statut,CommentaireSuperviseur:commentaire.trim(),DateDerniereDecision:maintenant()}]]);}
export async function definirEcheance(action:ActionMetier,dateIso:string,utilisateur:UtilisateurCourant):Promise<void>{const api=exigerApi();if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul un superviseur ou un administrateur peut définir une échéance.");if(!dateIso)throw new Error("Sélectionnez une date d’échéance.");const echeance=Math.floor(new Date(`${dateIso}T00:00:00Z`).getTime()/1000);if(!Number.isFinite(echeance))throw new Error("La date d’échéance est invalide.");await api.applyUserActions([["UpdateRecord","ActionsProgres",action.id,{Echeance:echeance}]]);try{await api.applyUserActions([["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,TypeObjet:"ACTION_PROGRES",ObjetUid:action.uid||String(action.id),Action:"ECHEANCE_MODIFIEE",Resume:`Échéance fixée au ${dateIso}`}]]);}catch{}}
export async function debloquerEvaluationRecruteur(recruteurId:number,utilisateur:UtilisateurCourant):Promise<void>{const api=exigerApi();if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul un superviseur ou un administrateur peut autoriser une nouvelle auto-évaluation.");const dateDeblocage=maintenant();await api.applyUserActions([["UpdateRecord","Utilisateurs",recruteurId,{DateDeblocageEvaluation:dateDeblocage}]]);try{await api.applyUserActions([["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,TypeObjet:"UTILISATEUR",ObjetUid:String(recruteurId),Action:"DEBLOCAGE_EVALUATION",Resume:"Nouvelle auto-évaluation autorisée par le superviseur"}]]);}catch{}}
export async function urlPieceJointe(attachment:number):Promise<string>{const api=exigerApi();if(!api.getAccessToken)throw new Error("Cette version de Grist ne permet pas l’ouverture sécurisée du PDF.");const{baseUrl,token}=await api.getAccessToken({readOnly:true});return`${baseUrl}/attachments/${attachment}/download?auth=${encodeURIComponent(token)}`;}
export async function journaliserConsultation(versionId:number,actionId:number|null,utilisateur:UtilisateurCourant,type:"OUVERTURE"|"TELECHARGEMENT"):Promise<void>{const api=exigerApi(),utilisateurs=await api.fetchTable("Utilisateurs"),i=(utilisateurs.id??[]).findIndex(v=>nombre(v)===utilisateur.id),perimetre=referenceId(utilisateurs.PerimetrePrincipal?.[i]);await api.applyUserActions([["AddRecord","ConsultationsFiches",null,{Uid:crypto.randomUUID(),FicheVersion:versionId,ActionProgres:actionId,Recruteur:utilisateur.id,Perimetre:perimetre,TypeEvenement:type,DateEvenement:maintenant()}]]);}

function exigerApi(){const api=obtenirDocApiGrist();if(!api)throw new Error("Cette opération est disponible uniquement depuis le widget Grist.");return api;}function libelles(t:TableGrist,c:string){const m=new Map<number,string>();(t.id??[]).forEach((v,i)=>{const id=nombre(v);if(id)m.set(id,texte(t[c]?.[i]));});return m;}function referenceId(v:unknown):number|null{if(typeof v==="number"&&v>0)return v;if(Array.isArray(v)){for(let i=v.length-1;i>=0;i--)if(typeof v[i]==="number"&&(v[i]as number)>0)return v[i]as number;}return null;}function attachmentId(v:unknown){return referenceId(v);}function normaliserNiveau(v:unknown):Niveau|null{const n=texte(v).toUpperCase();return n==="ROUGE"||n==="ORANGE"||n==="VERT"?n:null;}function nombre(v:unknown):number|null{return typeof v==="number"&&Number.isFinite(v)?v:null;}function texte(v:unknown):string{return typeof v==="string"?v:"";}function booleen(v:unknown):boolean{return v===true||v===1;}function dateHeure(v:unknown):string{const n=nombre(v);return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"—";}function dateSeule(n:number):string{return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"Sans échéance";}function maintenant(){return Math.floor(Date.now()/1000);}
function demoTables():[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]{return[{id:[2,3,4],Prenom:["Camille","Morgan","Sam"],Nom:["BERNARD","ROBERT","DURAND"],Email:["camille@example.invalid","morgan@example.invalid","sam@example.invalid"],Role:["SUPERVISEUR","RECRUTEUR","RECRUTEUR"],PerimetrePrincipal:[1,1,1],DateDeblocageEvaluation:[0,0,1_750_000_000],Actif:[true,true,true]},{id:[1],Nom:["SDIS 33 groupement NORD"]},{id:[1,2],Uid:["EVAL-1","EVAL-2"],Recruteur:[3,4],Perimetre:[1,1],Statut:["VALIDEE","BROUILLON"],ProgressionComplete:[100,46],DateDebut:[1_730_000_000,1_740_000_000],DateValidation:[1_730_100_000,null]},{id:[1,2],Evaluation:[1,1],Indicateur:[1,2],Niveau:["ROUGE","ORANGE"],CommentaireRecruteur:["",""]},{id:[1,2],Code:["IND_01","IND_02"],Titre:["Délai du premier contact","Qualité du premier accueil"]},{id:[1,2],Uid:["ACT-1","ACT-2"],Recruteur:[3,3],Perimetre:[1,1],Indicateur:[1,2],NiveauInitial:["ROUGE","ORANGE"],NiveauCourant:["ROUGE","ORANGE"],Statut:["EN_ATTENTE_VALIDATION","EN_COURS"],Echeance:[1_800_000_000,1_700_000_000],CommentaireRecruteur:["Mise en place d’un rappel sous 72 h","Travail engagé"],CommentaireSuperviseur:["",""] ,PriseEnCompteFiche:[true,false],FicheVersion:[1,null]},{id:[1],ActionProgres:[2],Recruteur:[3],Superviseur:[2],Decision:["COMPLEMENT_DEMANDE"],AncienNiveau:["ORANGE"],NouveauNiveau:[null],Commentaire:["Ajouter un exemple concret"],DateDecision:[1_750_000_000]},{id:[1],Fiche:[1],NumeroVersion:["1.0"],NomFichier:["premier-contact.pdf"],FichierPDF:[["L",101]],EstPubliee:[true]},{id:[1],Code:["FICHE_IND_01"],Titre:["Réussir le premier contact"],Description:["Repères pratiques"],VersionActive:[1],Statut:["PUBLIEE"],Actif:[true]},{id:[1],Fiche:[1],Indicateur:[1],DeclencheRouge:[true],DeclencheOrange:[false],Actif:[true]}];}
