import { obtenirDocApiGrist, TableGrist } from "./grist-context.js";
import { Niveau } from "./evaluation-data.js";
import { UtilisateurCourant } from "./portal-data.js";

export interface ProfilMetier { id:number; nom:string; email:string; role:string; perimetre:string; actif:boolean; }
export interface EvaluationMetier { id:number; uid:string; recruteurId:number; recruteur:string; perimetre:string; statut:string; progression:number; dateDebut:string; dateValidation:string; reponses:readonly ReponseMetier[]; }
export interface ReponseMetier { id:number; evaluationId:number; indicateurId:number; indicateur:string; codeIndicateur:string; niveau:Niveau; commentaire:string; }
export interface ActionMetier { id:number; uid:string; recruteurId:number; recruteur:string; perimetre:string; indicateur:string; codeIndicateur:string; niveauInitial:Niveau; niveauCourant:Niveau; statut:string; echeance:string; echeanceTimestamp:number; commentaireRecruteur:string; commentaireSuperviseur:string; ficheVersionId:number|null; fiche:string; version:string; nomFichier:string; attachmentId:number|null; }
export interface ValidationMetier { id:number; actionId:number; recruteur:string; superviseur:string; decision:string; ancienNiveau:Niveau; nouveauNiveau:Niveau|null; commentaire:string; date:string; }
export interface DonneesOperationnelles { profils:readonly ProfilMetier[]; evaluations:readonly EvaluationMetier[]; actions:readonly ActionMetier[]; validations:readonly ValidationMetier[]; }
export type DecisionValidation="VALIDEE"|"COMPLEMENT_DEMANDE"|"REFUSEE";

const TABLES=["Utilisateurs","Perimetres","Evaluations","Reponses","Indicateurs","ActionsProgres","Validations","FicheVersions","FichesEnseignement"] as const;

export async function chargerDonneesOperationnelles():Promise<DonneesOperationnelles>{
  const api=obtenirDocApiGrist();
  if(!api)return construireDonneesOperationnelles(...demoTables());
  const [utilisateurs,perimetres,evaluations,reponses,indicateurs,actions,validations,versions,fiches]=await Promise.all([
    api.fetchTable(TABLES[0]),api.fetchTable(TABLES[1]),api.fetchTable(TABLES[2]),api.fetchTable(TABLES[3]),api.fetchTable(TABLES[4]),api.fetchTable(TABLES[5]),api.fetchTable(TABLES[6]),api.fetchTable(TABLES[7]),api.fetchTable(TABLES[8]),
  ]);
  return construireDonneesOperationnelles(utilisateurs,perimetres,evaluations,reponses,indicateurs,actions,validations,versions,fiches);
}

export function construireDonneesOperationnelles(utilisateurs:TableGrist,perimetres:TableGrist,evaluations:TableGrist,reponses:TableGrist,indicateurs:TableGrist,actions:TableGrist,validations:TableGrist,versions:TableGrist,fiches:TableGrist):DonneesOperationnelles{
  const nomsPerimetres=libelles(perimetres,"Nom"), nomsIndicateurs=libelles(indicateurs,"Titre"), codesIndicateurs=libelles(indicateurs,"Code"), nomsFiches=libelles(fiches,"Titre"), codesFiches=libelles(fiches,"Code");
  const profils:ProfilMetier[]=[];const nomsUtilisateurs=new Map<number,string>();
  (utilisateurs.id??[]).forEach((v,i)=>{const id=nombre(v);if(!id)return;const nom=`${texte(utilisateurs.Prenom?.[i])} ${texte(utilisateurs.Nom?.[i])}`.trim()||texte(utilisateurs.Email?.[i]);nomsUtilisateurs.set(id,nom);profils.push({id,nom,email:texte(utilisateurs.Email?.[i]),role:texte(utilisateurs.Role?.[i]),perimetre:nomsPerimetres.get(referenceId(utilisateurs.PerimetrePrincipal?.[i])??0)||"Non renseigné",actif:booleen(utilisateurs.Actif?.[i])});});
  const reponsesNormalisees:ReponseMetier[]=(reponses.id??[]).flatMap((v,i)=>{const id=nombre(v),evaluationId=referenceId(reponses.Evaluation?.[i]),indicateurId=referenceId(reponses.Indicateur?.[i]),niveau=normaliserNiveau(reponses.Niveau?.[i]);if(!id||!evaluationId||!indicateurId||!niveau)return[];return[{id,evaluationId,indicateurId,indicateur:nomsIndicateurs.get(indicateurId)||`Indicateur ${indicateurId}`,codeIndicateur:codesIndicateurs.get(indicateurId)||"",niveau,commentaire:texte(reponses.CommentaireRecruteur?.[i])}];});
  const evaluationsNormalisees:EvaluationMetier[]=(evaluations.id??[]).flatMap((v,i)=>{const id=nombre(v),recruteurId=referenceId(evaluations.Recruteur?.[i]);if(!id||!recruteurId)return[];return[{id,uid:texte(evaluations.Uid?.[i]),recruteurId,recruteur:nomsUtilisateurs.get(recruteurId)||`Utilisateur ${recruteurId}`,perimetre:nomsPerimetres.get(referenceId(evaluations.Perimetre?.[i])??0)||"Non renseigné",statut:texte(evaluations.Statut?.[i]),progression:nombre(evaluations.ProgressionComplete?.[i])??0,dateDebut:dateHeure(evaluations.DateDebut?.[i]),dateValidation:dateHeure(evaluations.DateValidation?.[i]),reponses:reponsesNormalisees.filter(r=>r.evaluationId===id)}];}).sort((a,b)=>b.id-a.id);
  const versionInfos=new Map<number,{fiche:string;version:string;nom:string;attachment:number|null}>();(versions.id??[]).forEach((v,i)=>{const id=nombre(v),ficheId=referenceId(versions.Fiche?.[i]);if(!id)return;versionInfos.set(id,{fiche:(ficheId&&(nomsFiches.get(ficheId)||codesFiches.get(ficheId)))||"Fiche pédagogique",version:texte(versions.NumeroVersion?.[i]),nom:texte(versions.NomFichier?.[i]),attachment:attachmentId(versions.FichierPDF?.[i])});});
  const actionsNormalisees:ActionMetier[]=(actions.id??[]).flatMap((v,i)=>{const id=nombre(v),recruteurId=referenceId(actions.Recruteur?.[i]),indicateurId=referenceId(actions.Indicateur?.[i]),niveauInitial=normaliserNiveau(actions.NiveauInitial?.[i]),niveauCourant=normaliserNiveau(actions.NiveauCourant?.[i]);if(!id||!recruteurId||!niveauInitial||!niveauCourant)return[];const ficheVersionId=referenceId(actions.FicheVersion?.[i]),info=ficheVersionId?versionInfos.get(ficheVersionId):undefined;const echeanceTimestamp=nombre(actions.Echeance?.[i])??0;return[{id,uid:texte(actions.Uid?.[i]),recruteurId,recruteur:nomsUtilisateurs.get(recruteurId)||`Utilisateur ${recruteurId}`,perimetre:nomsPerimetres.get(referenceId(actions.Perimetre?.[i])??0)||"Non renseigné",indicateur:nomsIndicateurs.get(indicateurId??0)||`Indicateur ${indicateurId??""}`,codeIndicateur:codesIndicateurs.get(indicateurId??0)||"",niveauInitial,niveauCourant,statut:texte(actions.Statut?.[i]),echeance:dateSeule(echeanceTimestamp),echeanceTimestamp,commentaireRecruteur:texte(actions.CommentaireRecruteur?.[i]),commentaireSuperviseur:texte(actions.CommentaireSuperviseur?.[i]),ficheVersionId:ficheVersionId??null,fiche:info?.fiche||"—",version:info?.version||"",nomFichier:info?.nom||"",attachmentId:info?.attachment??null}];}).sort((a,b)=>a.echeanceTimestamp-b.echeanceTimestamp);
  const validationsNormalisees:ValidationMetier[]=(validations.id??[]).flatMap((v,i)=>{const id=nombre(v),actionId=referenceId(validations.ActionProgres?.[i]),ancien=normaliserNiveau(validations.AncienNiveau?.[i]);if(!id||!actionId||!ancien)return[];return[{id,actionId,recruteur:nomsUtilisateurs.get(referenceId(validations.Recruteur?.[i])??0)||"—",superviseur:nomsUtilisateurs.get(referenceId(validations.Superviseur?.[i])??0)||"—",decision:texte(validations.Decision?.[i]),ancienNiveau:ancien,nouveauNiveau:normaliserNiveau(validations.NouveauNiveau?.[i]),commentaire:texte(validations.Commentaire?.[i]),date:dateHeure(validations.DateDecision?.[i])}];}).sort((a,b)=>b.id-a.id);
  return{profils:profils.sort((a,b)=>a.nom.localeCompare(b.nom,"fr")),evaluations:evaluationsNormalisees,actions:actionsNormalisees,validations:validationsNormalisees};
}

export async function declarerProgression(actionId:number,commentaire:string):Promise<void>{const api=exigerApi();if(!commentaire.trim())throw new Error("Décrivez les progrès réalisés avant d’envoyer la demande.");await api.applyUserActions([["UpdateRecord","ActionsProgres",actionId,{Statut:"EN_ATTENTE_VALIDATION",CommentaireRecruteur:commentaire.trim(),DatePriseEnCompte:maintenant()}]]);}
export async function demarrerAction(actionId:number):Promise<void>{const api=exigerApi();await api.applyUserActions([["UpdateRecord","ActionsProgres",actionId,{Statut:"EN_COURS",DatePriseEnCompte:maintenant()}]]);}
export async function deciderAction(action:ActionMetier,decision:DecisionValidation,nouveau:Niveau|null,commentaire:string,utilisateur:UtilisateurCourant):Promise<void>{const api=exigerApi();if(decision==="VALIDEE"&&!nouveau)throw new Error("Sélectionnez le nouveau niveau validé.");if(decision!=="VALIDEE"&&!commentaire.trim())throw new Error("Un commentaire est obligatoire pour un complément ou un refus.");const statut=decision==="VALIDEE"?"PROGRESSION_VALIDEE":decision==="COMPLEMENT_DEMANDE"?"COMPLEMENT_DEMANDE":"VALIDATION_REFUSEE";await api.applyUserActions([["AddRecord","Validations",null,{Uid:crypto.randomUUID(),ActionProgres:action.id,Recruteur:action.recruteurId,Superviseur:utilisateur.id,Decision:decision,NouveauNiveau:nouveau,Commentaire:commentaire.trim()}],["UpdateRecord","ActionsProgres",action.id,{NiveauCourant:nouveau??action.niveauCourant,Statut:statut,CommentaireSuperviseur:commentaire.trim(),DateDerniereDecision:maintenant()}]]);}
export async function urlPieceJointe(attachment:number):Promise<string>{const api=exigerApi();if(!api.getAccessToken)throw new Error("Cette version de Grist ne permet pas l’ouverture sécurisée du PDF.");const{baseUrl,token}=await api.getAccessToken({readOnly:true});return`${baseUrl}/attachments/${attachment}/download?auth=${encodeURIComponent(token)}`;}
export async function journaliserConsultation(versionId:number,action:ActionMetier,utilisateur:UtilisateurCourant,type:"OUVERTURE"|"TELECHARGEMENT"|"PRISE_EN_COMPTE"):Promise<void>{const api=exigerApi();await api.applyUserActions([["AddRecord","ConsultationsFiches",null,{Uid:crypto.randomUUID(),FicheVersion:versionId,ActionProgres:action.id,Recruteur:utilisateur.id,TypeEvenement:type}]]);}

function exigerApi(){const api=obtenirDocApiGrist();if(!api)throw new Error("Cette opération est disponible uniquement depuis le widget Grist.");return api;}function libelles(t:TableGrist,c:string){const m=new Map<number,string>();(t.id??[]).forEach((v,i)=>{const id=nombre(v);if(id)m.set(id,texte(t[c]?.[i]));});return m;}function referenceId(v:unknown):number|null{if(typeof v==="number"&&v>0)return v;if(Array.isArray(v)){for(let i=v.length-1;i>=0;i--)if(typeof v[i]==="number"&&(v[i]as number)>0)return v[i]as number;}return null;}function attachmentId(v:unknown){return referenceId(v);}function normaliserNiveau(v:unknown):Niveau|null{const n=texte(v).toUpperCase();return n==="ROUGE"||n==="ORANGE"||n==="VERT"?n:null;}function nombre(v:unknown):number|null{return typeof v==="number"&&Number.isFinite(v)?v:null;}function texte(v:unknown):string{return typeof v==="string"?v:"";}function booleen(v:unknown):boolean{return v===true||v===1;}function dateHeure(v:unknown):string{const n=nombre(v);return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"—";}function dateSeule(n:number):string{return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"Sans échéance";}function maintenant(){return Math.floor(Date.now()/1000);}
function demoTables():[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]{return[{id:[2,3,4],Prenom:["Camille","Morgan","Sam"],Nom:["BERNARD","ROBERT","DURAND"],Email:["camille@example.invalid","morgan@example.invalid","sam@example.invalid"],Role:["SUPERVISEUR","RECRUTEUR","RECRUTEUR"],PerimetrePrincipal:[1,1,1],Actif:[true,true,true]},{id:[1],Nom:["SDIS 33 groupement NORD"]},{id:[1,2],Uid:["EVAL-1","EVAL-2"],Recruteur:[3,4],Perimetre:[1,1],Statut:["VALIDEE","BROUILLON"],ProgressionComplete:[100,46],DateDebut:[1_730_000_000,1_740_000_000],DateValidation:[1_730_100_000,null]},{id:[1,2],Evaluation:[1,1],Indicateur:[1,2],Niveau:["ROUGE","ORANGE"],CommentaireRecruteur:["",""]},{id:[1,2],Code:["IND_01","IND_02"],Titre:["Délai du premier contact","Qualité du premier accueil"]},{id:[1,2],Uid:["ACT-1","ACT-2"],Recruteur:[3,3],Perimetre:[1,1],Indicateur:[1,2],NiveauInitial:["ROUGE","ORANGE"],NiveauCourant:["ROUGE","ORANGE"],Statut:["EN_ATTENTE_VALIDATION","EN_COURS"],Echeance:[1_800_000_000,1_700_000_000],CommentaireRecruteur:["Mise en place d’un rappel sous 72 h","Travail engagé"],CommentaireSuperviseur:["",""] ,FicheVersion:[1,null]},{id:[1],ActionProgres:[2],Recruteur:[3],Superviseur:[2],Decision:["COMPLEMENT_DEMANDE"],AncienNiveau:["ORANGE"],NouveauNiveau:[null],Commentaire:["Ajouter un exemple concret"],DateDecision:[1_750_000_000]},{id:[1],Fiche:[1],NumeroVersion:["1.0"],NomFichier:["premier-contact.pdf"],FichierPDF:[["L",101]]},{id:[1],Code:["FICHE_IND_01"],Titre:["Réussir le premier contact"]}];}
