import { urlPdfPresentationDemo } from "./demo-pdf.js";
import { obtenirDocApiGrist, TableGrist } from "./grist-context.js";
import { Niveau } from "./evaluation-data.js";
import { UtilisateurCourant } from "./portal-data.js";
import { formaterNumeroVersion } from "./version-number.js";

export interface ProfilMetier { id:number; nom:string; email:string; role:string; perimetre:string; actif:boolean; dateDeblocageEvaluationTimestamp:number; }
export interface EvaluationMetier { id:number; uid:string; recruteurId:number; recruteur:string; perimetre:string; statut:string; progression:number; dateDebut:string; dateValidation:string; dateValidationTimestamp:number; referentielVersion?:string; reponses:readonly ReponseMetier[]; }
export interface ReponseMetier { id:number; evaluationId:number; indicateurId:number; indicateur:string; codeIndicateur:string; niveau:Niveau; commentaire:string; }
export interface ActionMetier { id:number; uid:string; recruteurId:number; recruteur:string; perimetreId:number|null; perimetre:string; indicateur:string; codeIndicateur:string; niveauInitial:Niveau; niveauCourant:Niveau; statut:string; echeance:string; echeanceTimestamp:number; commentaireRecruteur:string; commentaireSuperviseur:string; priseEnCompteFiche:boolean; ficheVersionId:number|null; fiche:string; version:string; nomFichier:string; attachmentId:number|null; }
export interface FicheDisponible { id:number; versionId:number; code:string; titre:string; description:string; indicateurId:number; indicateur:string; codeIndicateur:string; niveau:Niveau; version:string; nomFichier:string; attachmentId:number; }
export interface ValidationMetier { id:number; actionId:number; recruteur:string; superviseur:string; indicateur:string; codeIndicateur:string; version:string; decision:string; ancienNiveau:Niveau; nouveauNiveau:Niveau|null; commentaire:string; date:string; }
export interface DonneesOperationnelles { profils:readonly ProfilMetier[]; evaluations:readonly EvaluationMetier[]; actions:readonly ActionMetier[]; validations:readonly ValidationMetier[]; fiches:readonly FicheDisponible[]; }
export type DecisionValidation="VALIDEE"|"COMPLEMENT_DEMANDE"|"REFUSEE";

export function peutConsulterFiches(evaluations:readonly EvaluationMetier[],utilisateurId:number):boolean{return evaluations.some(e=>e.recruteurId===utilisateurId&&e.statut==="VALIDEE"&&e.progression===100);}

const TABLES_BASE=["Utilisateurs","Perimetres","Evaluations","Reponses","Indicateurs"] as const;
const TABLES_PEDAGOGIQUES=["FicheVersions","FichesEnseignement","FicheIndicateurs"] as const;
type TableOperationnelle=typeof TABLES_BASE[number]|typeof TABLES_PEDAGOGIQUES[number]|"ActionsProgres"|"Validations";

const TABLES_PAR_PAGE:Record<string,readonly TableOperationnelle[]>={
  resultats:TABLES_BASE,
  historique:[...TABLES_BASE,"Validations"],
  fiches:TABLES_BASE,
  progression:[...TABLES_BASE,"ActionsProgres"],
  recruteurs:TABLES_BASE,
  "gestion-recruteurs":TABLES_BASE,
  "evaluations-recruteurs":[...TABLES_BASE,"ActionsProgres"],
  "progres-a-valider":[...TABLES_BASE,"ActionsProgres","Validations",...TABLES_PEDAGOGIQUES],
  "progres-ouverts":[...TABLES_BASE,"ActionsProgres","Validations",...TABLES_PEDAGOGIQUES],
  echeances:[...TABLES_BASE,"ActionsProgres",...TABLES_PEDAGOGIQUES],
};

export async function chargerDonneesOperationnelles(page:string,utilisateur:UtilisateurCourant):Promise<DonneesOperationnelles>{
  const api=obtenirDocApiGrist();
  if(!api){
    const tables=demoTables();
    appliquerHistoriqueDemo(tables);
    appliquerEvaluationDemo(tables);
    appliquerValidationsDemo(tables);
    return construireDonneesOperationnelles(...tables);
  }
  const tablesDemandees=new Set<TableOperationnelle>(TABLES_PAR_PAGE[page]??TABLES_BASE);
  const tables=await chargerTables(api,tablesDemandees);
  const accesPedagogiqueRequis=(page==="fiches"||page==="progression")&&evaluationValideeComplete(tables.Evaluations,utilisateur.id);
  if(accesPedagogiqueRequis){
    Object.assign(tables,await chargerTables(api,new Set(TABLES_PEDAGOGIQUES)));
  }
  return construireDonneesOperationnelles(
    tables.Utilisateurs??{},tables.Perimetres??{},tables.Evaluations??{},tables.Reponses??{},tables.Indicateurs??{},
    tables.ActionsProgres??{},tables.Validations??{},tables.FicheVersions??{},tables.FichesEnseignement??{},tables.FicheIndicateurs??{},
  );
}

async function chargerTables(api:{fetchTable:(tableId:string)=>Promise<TableGrist>},tables:ReadonlySet<TableOperationnelle>):Promise<Partial<Record<TableOperationnelle,TableGrist>>>{
  const entrees=await Promise.all([...tables].map(async table=>[table,await api.fetchTable(table)] as const));
  return Object.fromEntries(entrees) as Partial<Record<TableOperationnelle,TableGrist>>;
}

function evaluationValideeComplete(evaluations:TableGrist|undefined,utilisateurId:number):boolean{
  return (evaluations?.id??[]).some((_,i)=>referenceId(evaluations?.Recruteur?.[i])===utilisateurId&&texte(evaluations?.Statut?.[i])==="VALIDEE"&&(nombre(evaluations?.ProgressionComplete?.[i])??0)===100);
}

export function construireDonneesOperationnelles(utilisateurs:TableGrist,perimetres:TableGrist,evaluations:TableGrist,reponses:TableGrist,indicateurs:TableGrist,actions:TableGrist,validations:TableGrist,versions:TableGrist,fiches:TableGrist,liaisons:TableGrist={id:[]}):DonneesOperationnelles{
  const nomsPerimetres=libelles(perimetres,"Nom"), nomsIndicateurs=libelles(indicateurs,"Titre"), codesIndicateurs=libelles(indicateurs,"Code"), nomsFiches=libelles(fiches,"Titre"), codesFiches=libelles(fiches,"Code");
  const profils:ProfilMetier[]=[];const nomsUtilisateurs=new Map<number,string>();
  (utilisateurs.id??[]).forEach((v,i)=>{const id=nombre(v);if(!id)return;const nom=`${texte(utilisateurs.Prenom?.[i])} ${texte(utilisateurs.Nom?.[i])}`.trim()||texte(utilisateurs.Email?.[i]);nomsUtilisateurs.set(id,nom);profils.push({id,nom,email:texte(utilisateurs.Email?.[i]),role:texte(utilisateurs.Role?.[i]),perimetre:nomsPerimetres.get(referenceId(utilisateurs.PerimetrePrincipal?.[i])??0)||"Non renseigné",actif:booleen(utilisateurs.Actif?.[i]),dateDeblocageEvaluationTimestamp:nombre(utilisateurs.DateDeblocageEvaluation?.[i])??0});});
  const reponsesNormalisees:ReponseMetier[]=(reponses.id??[]).flatMap((v,i)=>{const id=nombre(v),evaluationId=referenceId(reponses.Evaluation?.[i]),indicateurId=referenceId(reponses.Indicateur?.[i]),niveau=normaliserNiveau(reponses.Niveau?.[i]);if(!id||!evaluationId||!indicateurId||!niveau)return[];return[{id,evaluationId,indicateurId,indicateur:nomsIndicateurs.get(indicateurId)||`Indicateur ${indicateurId}`,codeIndicateur:codesIndicateurs.get(indicateurId)||"",niveau,commentaire:texte(reponses.CommentaireRecruteur?.[i])}];});
  const evaluationsNormalisees:EvaluationMetier[]=(evaluations.id??[]).flatMap((v,i)=>{const id=nombre(v),recruteurId=referenceId(evaluations.Recruteur?.[i]);if(!id||!recruteurId)return[];const dateValidationTimestamp=nombre(evaluations.DateValidation?.[i])??nombre(evaluations.UpdatedAt?.[i])??0;return[{id,uid:texte(evaluations.Uid?.[i]),recruteurId,recruteur:nomsUtilisateurs.get(recruteurId)||`Utilisateur ${recruteurId}`,perimetre:nomsPerimetres.get(referenceId(evaluations.Perimetre?.[i])??0)||"Non renseigné",statut:texte(evaluations.Statut?.[i]),progression:nombre(evaluations.ProgressionComplete?.[i])??0,dateDebut:dateHeure(evaluations.DateDebut?.[i]),dateValidation:dateHeure(evaluations.DateValidation?.[i]),dateValidationTimestamp,referentielVersion:texte(evaluations.ReferentielVersion?.[i])||"non renseigné",reponses:reponsesNormalisees.filter(r=>r.evaluationId===id)}];}).sort((a,b)=>b.id-a.id);
  const versionInfos=new Map<number,{ficheId:number|null;fiche:string;version:string;nom:string;attachment:number|null;publiee:boolean}>();(versions.id??[]).forEach((v,i)=>{const id=nombre(v),ficheId=referenceId(versions.Fiche?.[i]);if(!id)return;versionInfos.set(id,{ficheId,fiche:(ficheId&&(nomsFiches.get(ficheId)||codesFiches.get(ficheId)))||"Fiche pédagogique",version:formaterNumeroVersion(versions.NumeroVersion?.[i]),nom:texte(versions.NomFichier?.[i]),attachment:attachmentId(versions.FichierPDF?.[i]),publiee:booleen(versions.EstPubliee?.[i])});});
  const actionsNormalisees:ActionMetier[]=(actions.id??[]).flatMap((v,i)=>{const id=nombre(v),recruteurId=referenceId(actions.Recruteur?.[i]),perimetreId=referenceId(actions.Perimetre?.[i]),indicateurId=referenceId(actions.Indicateur?.[i]),niveauInitial=normaliserNiveau(actions.NiveauInitial?.[i]),niveauCourant=normaliserNiveau(actions.NiveauCourant?.[i]);if(!id||!recruteurId||!niveauInitial||!niveauCourant)return[];const ficheVersionId=referenceId(actions.FicheVersion?.[i]),info=ficheVersionId?versionInfos.get(ficheVersionId):undefined;const echeanceTimestamp=nombre(actions.Echeance?.[i])??0;return[{id,uid:texte(actions.Uid?.[i]),recruteurId,recruteur:nomsUtilisateurs.get(recruteurId)||`Utilisateur ${recruteurId}`,perimetreId,perimetre:nomsPerimetres.get(perimetreId??0)||"Non renseigné",indicateur:nomsIndicateurs.get(indicateurId??0)||`Indicateur ${indicateurId??""}`,codeIndicateur:codesIndicateurs.get(indicateurId??0)||"",niveauInitial,niveauCourant,statut:texte(actions.Statut?.[i]),echeance:dateSeule(echeanceTimestamp),echeanceTimestamp,commentaireRecruteur:texte(actions.CommentaireRecruteur?.[i]),commentaireSuperviseur:texte(actions.CommentaireSuperviseur?.[i]),priseEnCompteFiche:booleen(actions.PriseEnCompteFiche?.[i]),ficheVersionId:ficheVersionId??null,fiche:info?.fiche||"—",version:info?.version||"",nomFichier:info?.nom||"",attachmentId:info?.attachment??null}];}).sort((a,b)=>a.echeanceTimestamp-b.echeanceTimestamp);
  const actionsParId=new Map(actionsNormalisees.map(action=>[action.id,action]));
  const validationsNormalisees:ValidationMetier[]=(validations.id??[]).flatMap((v,i)=>{const id=nombre(v),actionId=referenceId(validations.ActionProgres?.[i]),ancien=normaliserNiveau(validations.AncienNiveau?.[i]);if(!id||!actionId||!ancien)return[];const action=actionsParId.get(actionId);return[{id,actionId,recruteur:nomsUtilisateurs.get(referenceId(validations.Recruteur?.[i])??0)||"—",superviseur:nomsUtilisateurs.get(referenceId(validations.Superviseur?.[i])??0)||"—",indicateur:action?.indicateur||"Indicateur non renseigné",codeIndicateur:action?.codeIndicateur||"",version:action?.version||"",decision:texte(validations.Decision?.[i]),ancienNiveau:ancien,nouveauNiveau:normaliserNiveau(validations.NouveauNiveau?.[i]),commentaire:texte(validations.Commentaire?.[i]),date:dateHeure(validations.DateDecision?.[i])}];}).sort((a,b)=>b.id-a.id);
  const fichesDisponibles:FicheDisponible[]=(fiches.id??[]).flatMap((v,i)=>{const id=nombre(v),versionId=referenceId(fiches.VersionActive?.[i]);if(!id||!versionId||texte(fiches.Statut?.[i])!=="PUBLIEE"||!booleen(fiches.Actif?.[i]))return[];const info=versionInfos.get(versionId);if(!info?.attachment||!info.publiee)return[];const li=(liaisons.id??[]).findIndex((_,x)=>referenceId(liaisons.Fiche?.[x])===id&&booleen(liaisons.Actif?.[x]));const indicateurId=referenceId(liaisons.Indicateur?.[li]);const niveau:Niveau|null=booleen(liaisons.DeclencheRouge?.[li])?"ROUGE":booleen(liaisons.DeclencheOrange?.[li])?"ORANGE":null;if(!indicateurId||!niveau)return[];return[{id,versionId,code:codesFiches.get(id)||"",titre:nomsFiches.get(id)||"Fiche d’enseignement",description:texte(fiches.Description?.[i]),indicateurId,indicateur:nomsIndicateurs.get(indicateurId)||`Indicateur ${indicateurId}`,codeIndicateur:codesIndicateurs.get(indicateurId)||"",niveau,version:info.version,nomFichier:info.nom,attachmentId:info.attachment}];}).sort((a,b)=>a.code.localeCompare(b.code,"fr"));
  return{profils:profils.sort((a,b)=>a.nom.localeCompare(b.nom,"fr")),evaluations:evaluationsNormalisees,actions:actionsNormalisees,validations:validationsNormalisees,fiches:fichesDisponibles};
}

export async function declarerProgression(action:ActionMetier,commentaire:string,utilisateur:UtilisateurCourant,priseEnCompte:boolean):Promise<void>{const avecFiche=Boolean(action.ficheVersionId);if(avecFiche&&!priseEnCompte)throw new Error("Confirmez la prise en compte de la fiche d’enseignement avant de demander la validation.");const mention=avecFiche?"Prise en compte de la fiche d’enseignement réalisée":"Progression déclarée sans fiche d’enseignement disponible à cette date";if(!obtenirDocApiGrist()){return simulerAction(action.id,{Statut:"EN_ATTENTE_VALIDATION",CommentaireRecruteur:commentaire.trim()||mention,PriseEnCompteFiche:avecFiche&&priseEnCompte});}const api=exigerApi(),date=maintenant();const actions:unknown[][]=[["UpdateRecord","ActionsProgres",action.id,{Statut:"EN_ATTENTE_VALIDATION",CommentaireRecruteur:commentaire.trim()||mention,PriseEnCompteFiche:avecFiche&&priseEnCompte,DatePriseEnCompte:date}]];if(action.ficheVersionId)actions.push(["AddRecord","ConsultationsFiches",null,{Uid:crypto.randomUUID(),FicheVersion:action.ficheVersionId,ActionProgres:action.id,Recruteur:utilisateur.id,Perimetre:action.perimetreId,TypeEvenement:"PRISE_EN_COMPTE"}]);actions.push(["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:action.perimetreId,TypeObjet:"ACTION",ObjetUid:action.uid||String(action.id),Action:"PROGRESSION_DECLAREE",Resume:`Progression déclarée pour ${action.codeIndicateur}`}]);await api.applyUserActions(actions);}
export async function demarrerAction(action:ActionMetier,utilisateur:UtilisateurCourant):Promise<void>{if(!obtenirDocApiGrist())return simulerAction(action.id,{Statut:"EN_COURS"});const api=exigerApi();await api.applyUserActions([["UpdateRecord","ActionsProgres",action.id,{Statut:"EN_COURS",DatePriseEnCompte:maintenant()}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:action.perimetreId,TypeObjet:"ACTION",ObjetUid:action.uid||String(action.id),Action:"ACTION_DEMARREE",Resume:`Action ${action.codeIndicateur} démarrée`}] ]);}
export async function rouvrirAction(action:ActionMetier,utilisateur:UtilisateurCourant):Promise<void>{if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul le superviseur du périmètre ou un administrateur peut rouvrir une action refusée.");if(action.statut!=="VALIDATION_REFUSEE")throw new Error("Seule une action refusée peut être rouverte.");if(!action.perimetreId)throw new Error("Le périmètre de cette action est introuvable.");if(!obtenirDocApiGrist())return simulerAction(action.id,{Statut:"EN_COURS"});const api=exigerApi();await api.applyUserActions([["UpdateRecord","ActionsProgres",action.id,{Statut:"EN_COURS",DateDerniereDecision:maintenant()}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:action.perimetreId,TypeObjet:"ACTION",ObjetUid:action.uid||String(action.id),Action:"REOUVERTURE_APRES_REFUS",Resume:`Action ${action.codeIndicateur} rouverte pour correction`}]]);}
export async function deciderAction(action:ActionMetier,decision:DecisionValidation,nouveau:Niveau|null,commentaire:string,utilisateur:UtilisateurCourant):Promise<void>{if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul un superviseur ou un administrateur peut décider d’une progression.");if(decision==="VALIDEE"&&action.ficheVersionId&&!action.priseEnCompteFiche)throw new Error("La prise en compte de la fiche d’enseignement doit être déclarée avant validation.");if(decision==="VALIDEE"&&nouveau!=="VERT")throw new Error("La validation entraîne uniquement le passage au vert.");if(decision!=="VALIDEE"&&!commentaire.trim())throw new Error("Un commentaire est obligatoire pour un complément ou un refus.");if(!action.perimetreId)throw new Error("Le périmètre de cette action est introuvable.");if(!obtenirDocApiGrist()){const statut=decision==="VALIDEE"?"PROGRESSION_VALIDEE":decision==="COMPLEMENT_DEMANDE"?"COMPLEMENT_DEMANDE":"VALIDATION_REFUSEE";simulerAction(action.id,{Statut:statut,NiveauCourant:nouveau??action.niveauCourant,CommentaireSuperviseur:commentaire.trim()});enregistrerValidationDemo(action,decision,nouveau,commentaire,utilisateur);return;}const api=exigerApi();if(decision==="VALIDEE"&&action.ficheVersionId&&!action.priseEnCompteFiche)throw new Error("La prise en compte de la fiche d’enseignement doit être déclarée avant validation.");if(decision==="VALIDEE"&&nouveau!=="VERT")throw new Error("La validation entraîne uniquement le passage au vert.");if(decision!=="VALIDEE"&&!commentaire.trim())throw new Error("Un commentaire est obligatoire pour un complément ou un refus.");if(!action.perimetreId)throw new Error("Le périmètre de cette action est introuvable.");const statut=decision==="VALIDEE"?"PROGRESSION_VALIDEE":decision==="COMPLEMENT_DEMANDE"?"COMPLEMENT_DEMANDE":"VALIDATION_REFUSEE";const ancienNiveau=action.niveauCourant;await api.applyUserActions([["AddRecord","Validations",null,{Uid:crypto.randomUUID(),ActionProgres:action.id,Recruteur:action.recruteurId,Perimetre:action.perimetreId,Superviseur:utilisateur.id,Decision:decision,AncienNiveau:ancienNiveau,NouveauNiveau:nouveau,Commentaire:commentaire.trim()}],["UpdateRecord","ActionsProgres",action.id,{NiveauCourant:nouveau??ancienNiveau,Statut:statut,CommentaireSuperviseur:commentaire.trim(),DateDerniereDecision:maintenant()}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:action.perimetreId,TypeObjet:"ACTION",ObjetUid:action.uid||String(action.id),Action:`DECISION_${decision}`,Resume:`Décision ${decision} pour ${action.codeIndicateur}`}]]);}
export async function rattacherFicheManquante(actionId:number,ficheVersionId:number,utilisateur:UtilisateurCourant):Promise<void>{if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul un superviseur ou un administrateur peut rattacher une fiche.");if(!obtenirDocApiGrist()){const tables=demoTables(),actions=tables[5],versions=tables[7],ai=(actions.id??[]).findIndex(v=>nombre(v)===actionId);if(ai<0)throw new Error("L’action de progression est introuvable.");const versionExistante=referenceId(actions.FicheVersion?.[ai]);if(versionExistante===ficheVersionId)return;if(versionExistante)throw new Error("Une version est déjà rattachée à cette action et ne peut pas être remplacée.");const vi=(versions.id??[]).findIndex(v=>nombre(v)===ficheVersionId);if(vi<0||!booleen(versions.EstPubliee?.[vi]))throw new Error("La version sélectionnée n’est pas publiée.");simulerAction(actionId,{FicheVersion:ficheVersionId});return;}const api=exigerApi();const[actions,versions]=await Promise.all([api.fetchTable("ActionsProgres"),api.fetchTable("FicheVersions")]);const ai=(actions.id??[]).findIndex(v=>nombre(v)===actionId);if(ai<0)throw new Error("L’action de progression est introuvable.");const versionExistante=referenceId(actions.FicheVersion?.[ai]);if(versionExistante===ficheVersionId)return;if(versionExistante)throw new Error("Une version est déjà rattachée à cette action et ne peut pas être remplacée.");const vi=(versions.id??[]).findIndex(v=>nombre(v)===ficheVersionId);if(vi<0||!booleen(versions.EstPubliee?.[vi]))throw new Error("La version sélectionnée n’est pas publiée.");const uid=texte(actions.Uid?.[ai])||String(actionId);const perimetre=referenceId(actions.Perimetre?.[ai]);await api.applyUserActions([["UpdateRecord","ActionsProgres",actionId,{FicheVersion:ficheVersionId}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:perimetre,TypeObjet:"ACTION",ObjetUid:uid,Action:"RATTACHEMENT_FICHE",Resume:`Version pédagogique ${ficheVersionId} rattachée sans remplacement`}]]);}
export async function definirEcheance(action:ActionMetier,dateIso:string,utilisateur:UtilisateurCourant):Promise<void>{if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul un superviseur ou un administrateur peut définir une échéance.");if(!dateIso)throw new Error("Sélectionnez une date d’échéance.");const echeance=Math.floor(new Date(`${dateIso}T00:00:00Z`).getTime()/1000);if(!Number.isFinite(echeance))throw new Error("La date d’échéance est invalide.");if(!obtenirDocApiGrist())return simulerAction(action.id,{Echeance:echeance});const api=exigerApi();await api.applyUserActions([["UpdateRecord","ActionsProgres",action.id,{Echeance:echeance}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:action.perimetreId,TypeObjet:"ACTION",ObjetUid:action.uid||String(action.id),Action:"ECHEANCE_MODIFIEE",Resume:`Échéance fixée au ${dateIso}`}]]);}
export async function debloquerEvaluationRecruteur(recruteurId:number,utilisateur:UtilisateurCourant):Promise<void>{if(utilisateur.role!=="SUPERVISEUR"&&utilisateur.role!=="ADMIN")throw new Error("Seul un superviseur ou un administrateur peut autoriser une nouvelle auto-évaluation.");if(!obtenirDocApiGrist()){if(recruteurId===3){archiverEvaluationDemo();try{sessionStorage.removeItem("spv-demo-evaluation-v1");sessionStorage.removeItem(CLE_DEMO_ACTIONS);}catch{}return;}throw new Error("Ce recruteur fictif n’est pas déblocable dans ce scénario.");}const api=exigerApi();const dateDeblocage=maintenant();await api.applyUserActions([["UpdateRecord","Utilisateurs",recruteurId,{DateDeblocageEvaluation:dateDeblocage}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:utilisateur.id,Perimetre:null,TypeObjet:"UTILISATEUR",ObjetUid:String(recruteurId),Action:"DEBLOCAGE_EVALUATION",Resume:"Nouvelle auto-évaluation autorisée par le superviseur"}]]);}
export async function urlPieceJointe(attachment:number):Promise<string>{if(!obtenirDocApiGrist())return urlPdfPresentationDemo("Ressource associee au parcours de progression",`Piece de presentation ${attachment}`);const api=exigerApi();if(!api.getAccessToken)throw new Error("Cette version de Grist ne permet pas l’ouverture sécurisée du PDF.");const{baseUrl,token}=await api.getAccessToken({readOnly:true});return`${baseUrl}/attachments/${attachment}/download?auth=${encodeURIComponent(token)}`;}
export async function journaliserConsultation(versionId:number,actionId:number|null,utilisateur:UtilisateurCourant,type:"OUVERTURE"|"TELECHARGEMENT"):Promise<void>{if(!obtenirDocApiGrist())return;const api=exigerApi(),utilisateurs=await api.fetchTable("Utilisateurs"),i=(utilisateurs.id??[]).findIndex(v=>nombre(v)===utilisateur.id),perimetre=referenceId(utilisateurs.PerimetrePrincipal?.[i]);await api.applyUserActions([["AddRecord","ConsultationsFiches",null,{Uid:crypto.randomUUID(),FicheVersion:versionId,ActionProgres:actionId,Recruteur:utilisateur.id,Perimetre:perimetre,TypeEvenement:type}]]);}

function exigerApi(){const api=obtenirDocApiGrist();if(!api)throw new Error("Cette opération est disponible uniquement depuis le widget Grist.");return api;}function libelles(t:TableGrist,c:string){const m=new Map<number,string>();(t.id??[]).forEach((v,i)=>{const id=nombre(v);if(id)m.set(id,texte(t[c]?.[i]));});return m;}function referenceId(v:unknown):number|null{if(typeof v==="number"&&v>0)return v;if(Array.isArray(v)){for(let i=v.length-1;i>=0;i--)if(typeof v[i]==="number"&&(v[i]as number)>0)return v[i]as number;}return null;}function attachmentId(v:unknown){return referenceId(v);}function normaliserNiveau(v:unknown):Niveau|null{const n=texte(v).toUpperCase();return n==="ROUGE"||n==="ORANGE"||n==="VERT"?n:null;}function nombre(v:unknown):number|null{return typeof v==="number"&&Number.isFinite(v)?v:null;}function texte(v:unknown):string{return typeof v==="string"?v:"";}function booleen(v:unknown):boolean{return v===true||v===1;}function dateHeure(v:unknown):string{const n=nombre(v);return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"—";}function dateSeule(n:number):string{return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"Sans échéance";}function maintenant(){return Math.floor(Date.now()/1000);}
function appliquerEvaluationDemo(tables:[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]):void{
  try{
    const brut=sessionStorage.getItem("spv-demo-evaluation-v1"); if(!brut)return;
    const d=JSON.parse(brut) as {evaluationId:number|null;reponses:Record<string,Niveau>;statut:string|null};
    if(!d.evaluationId||d.statut!=="VALIDEE")return;
    const evaluationId=d.evaluationId;
    const indicateurs=tables[4], ids=new Map<string,number>(); (indicateurs.id??[]).forEach((v,i)=>{if(typeof v==="number")ids.set(texte(indicateurs.Code?.[i]),v);});
    const codes=Object.keys(d.reponses); const repIds=codes.map((_,i)=>evaluationId*100+i+1);
    const ajouter=(table:TableGrist,valeurs:Record<string,unknown>)=>{for(const [k,v] of Object.entries(valeurs))table[k]=(table[k]??[]).concat(v);};
    ajouter(tables[2],{id:d.evaluationId,Uid:`DEMO-EVAL-${d.evaluationId}`,Recruteur:3,Perimetre:1,Statut:"VALIDEE",ProgressionComplete:100,DateDebut:Math.floor(Date.now()/1000)-3600,DateValidation:Math.floor(Date.now()/1000),ReferentielVersion:"demo-session"});
    codes.forEach((code,i)=>ajouter(tables[3],{id:repIds[i],Evaluation:d.evaluationId,Indicateur:ids.get(code)??0,Niveau:d.reponses[code],CommentaireRecruteur:""}));
    const perfectibles=codes.filter(code=>d.reponses[code]!=="VERT"&&ids.has(code));
    tables[5]={id:perfectibles.map((_,i)=>9100+i),Uid:perfectibles.map((_,i)=>`DEMO-ACT-${i+1}`),Recruteur:perfectibles.map(()=>3),Perimetre:perfectibles.map(()=>1),Indicateur:perfectibles.map(code=>ids.get(code)!),NiveauInitial:perfectibles.map(code=>d.reponses[code]),NiveauCourant:perfectibles.map(code=>d.reponses[code]),Statut:perfectibles.map(()=>"A_FAIRE"),Echeance:perfectibles.map(()=>0),CommentaireRecruteur:perfectibles.map(()=>""),CommentaireSuperviseur:perfectibles.map(()=>""),PriseEnCompteFiche:perfectibles.map(()=>false),FicheVersion:perfectibles.map(code=>code==="IND_01"?1:null)};
    const memorisees=lireActionsDemo();if(memorisees)tables[5]=memorisees;else ecrireActionsDemo(tables[5]);
  }catch{}
}
const CLE_DEMO_HISTORIQUE="spv-demo-historique-v1", CLE_DEMO_VALIDATIONS="spv-demo-validations-v1";
function archiverEvaluationDemo():void{try{const brut=sessionStorage.getItem("spv-demo-evaluation-v1");if(!brut)return;const d=JSON.parse(brut);if(d?.statut!=="VALIDEE")return;const h=JSON.parse(sessionStorage.getItem(CLE_DEMO_HISTORIQUE)||"[]") as unknown[];h.push({...d,archiveeLe:maintenant()});sessionStorage.setItem(CLE_DEMO_HISTORIQUE,JSON.stringify(h));}catch{}}
function appliquerHistoriqueDemo(tables:[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]):void{try{const h=JSON.parse(sessionStorage.getItem(CLE_DEMO_HISTORIQUE)||"[]") as Array<{evaluationId:number;reponses:Record<string,Niveau>;statut:string;archiveeLe:number}>;if(!h.length)return;const ids=new Map<string,number>();(tables[4].id??[]).forEach((v,i)=>{if(typeof v==="number")ids.set(texte(tables[4].Code?.[i]),v);});for(const e of h){const eid=e.evaluationId||8000+(tables[2].id?.length??0);tables[2].id=(tables[2].id??[]).concat(eid);for(const [k,v] of Object.entries({Uid:`DEMO-HIST-${eid}`,Recruteur:3,Perimetre:1,Statut:"VALIDEE",ProgressionComplete:100,DateDebut:e.archiveeLe-3600,DateValidation:e.archiveeLe,ReferentielVersion:"demo-archive"})){tables[2][k]=(tables[2][k]??[]).concat(v);}for(const [code,niveau] of Object.entries(e.reponses)){const iid=ids.get(code);if(!iid)continue;const rid=eid*100+(tables[3].id??[]).filter((v)=>typeof v==="number"&&Math.floor((v as number)/100)===eid).length+1;tables[3].id=(tables[3].id??[]).concat(rid);for(const [k,v] of Object.entries({Evaluation:eid,Indicateur:iid,Niveau:niveau,CommentaireRecruteur:""})){tables[3][k]=(tables[3][k]??[]).concat(v);}}}}catch{}}
function enregistrerValidationDemo(action:ActionMetier,decision:DecisionValidation,nouveau:Niveau|null,commentaire:string,utilisateur:UtilisateurCourant):void{try{const v=JSON.parse(sessionStorage.getItem(CLE_DEMO_VALIDATIONS)||"[]") as any[];v.push({id:9600+v.length,ActionProgres:action.id,Recruteur:action.recruteurId,Superviseur:utilisateur.id,Decision:decision,AncienNiveau:action.niveauCourant,NouveauNiveau:nouveau,Commentaire:commentaire.trim(),DateDecision:maintenant()});sessionStorage.setItem(CLE_DEMO_VALIDATIONS,JSON.stringify(v));}catch{}}
function appliquerValidationsDemo(tables:[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]):void{try{const v=JSON.parse(sessionStorage.getItem(CLE_DEMO_VALIDATIONS)||"[]") as any[];if(!v.length)return;const keys=["id","ActionProgres","Recruteur","Superviseur","Decision","AncienNiveau","NouveauNiveau","Commentaire","DateDecision"];tables[6]=Object.fromEntries(keys.map(k=>[k,v.map(x=>x[k]??null)]));}catch{}}
const CLE_DEMO_ACTIONS="spv-demo-actions-v1";
function lireActionsDemo():TableGrist|null{try{const brut=sessionStorage.getItem(CLE_DEMO_ACTIONS);return brut?JSON.parse(brut) as TableGrist:null;}catch{return null;}}
function ecrireActionsDemo(t:TableGrist):void{try{sessionStorage.setItem(CLE_DEMO_ACTIONS,JSON.stringify(t));}catch{}}
function simulerAction(id:number,maj:Record<string,unknown>):void{const tables=demoTables();const t=tables[5],i=(t.id??[]).findIndex(v=>v===id);if(i<0)return;Object.entries(maj).forEach(([k,v])=>{if(!t[k])t[k]=Array((t.id??[]).length).fill(null);t[k]![i]=v;});ecrireActionsDemo(t);}function demoTables():[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]{const tables:[TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist,TableGrist]=[{id:[2,3,4],Prenom:["Camille","Morgan","Sam"],Nom:["BERNARD","ROBERT","DURAND"],Email:["camille.bernard@example.invalid","morgan.robert@example.invalid","sam.durand@example.invalid"],Role:["SUPERVISEUR","RECRUTEUR","RECRUTEUR"],PerimetrePrincipal:[1,1,1],DateDeblocageEvaluation:[0,0,1_750_000_000],Actif:[true,true,true]},{id:[1],Nom:["SDIS 33 groupement NORD"]},{id:[1,2],Uid:["EVAL-1","EVAL-2"],Recruteur:[3,4],Perimetre:[1,1],Statut:["VALIDEE","BROUILLON"],ProgressionComplete:[100,46],DateDebut:[1_730_000_000,1_740_000_000],DateValidation:[1_730_100_000,null]},{id:[1,2],Evaluation:[1,1],Indicateur:[1,2],Niveau:["ROUGE","ORANGE"],CommentaireRecruteur:["",""]},{id:[1,2,3,4,5,6,7,8,9,10,11,12,13],Code:["IND_01","IND_02","IND_03","IND_04","IND_05","IND_06","IND_07","IND_08","IND_09","IND_10","IND_11","IND_12","IND_13"],Titre:["Délai du premier contact","Qualité du premier accueil","Délai entre premier contact et décision","Communication sur les valeurs et engagements du SIS","Exploration des motivations (Pourquoi / Pour quoi)","Vérification de la disponibilité réelle","Adéquation aux valeurs SPV (avec mini-cas)","Évaluation de la compatibilité à 360 degrés (Ikigaï)","Transparence sur la réalité du métier","Présentation du parcours de formation (FISPV)","Implication du tuteur ou référent","Suivi post-engagement (première année)","Indicateurs de résultat (retour sur investissement)"]},{id:[1,2],Uid:["ACT-1","ACT-2"],Recruteur:[3,3],Perimetre:[1,1],Indicateur:[1,2],NiveauInitial:["ROUGE","ORANGE"],NiveauCourant:["ROUGE","ORANGE"],Statut:["EN_ATTENTE_VALIDATION","EN_COURS"],Echeance:[1_800_000_000,1_700_000_000],CommentaireRecruteur:["Mise en place d’un rappel sous 72 h","Travail engagé"],CommentaireSuperviseur:["",""] ,PriseEnCompteFiche:[true,false],FicheVersion:[1,null]},{id:[1],ActionProgres:[2],Recruteur:[3],Superviseur:[2],Decision:["COMPLEMENT_DEMANDE"],AncienNiveau:["ORANGE"],NouveauNiveau:[null],Commentaire:["Ajouter un exemple concret"],DateDecision:[1_750_000_000]},{id:[1],Fiche:[1],NumeroVersion:["1.0"],NomFichier:["premier-contact.pdf"],FichierPDF:[["L",101]],EstPubliee:[true]},{id:[1],Code:["FICHE_IND_01"],Titre:["Réussir le premier contact"],Description:["Repères pratiques"],VersionActive:[1],Statut:["PUBLIEE"],Actif:[true]},{id:[1],Fiche:[1],Indicateur:[1],DeclencheRouge:[true],DeclencheOrange:[false],Actif:[true]}];const memorisees=lireActionsDemo();if(memorisees)tables[5]=memorisees;return tables;}
