import React, { useEffect, useState } from "react";
import { chargerReglagesPerimetres, enregistrerReglage, ReglagePerimetre } from "./parametrage-data.js";
import { UtilisateurCourant } from "./portal-data.js";

type Etat = { statut: "chargement" } | { statut: "erreur"; message: string } | { statut: "pret"; reglages: readonly ReglagePerimetre[] };

export function ModuleParametrage({ utilisateur }: { utilisateur: UtilisateurCourant }) {
  const [etat, setEtat] = useState<Etat>({ statut: "chargement" }); const [tentative, setTentative] = useState(0); const [enregistrement, setEnregistrement] = useState<number | null>(null); const [message, setMessage] = useState<{ type: "succes" | "erreur"; texte: string } | null>(null);
  useEffect(() => { let actif = true; setEtat({ statut: "chargement" }); chargerReglagesPerimetres(utilisateur).then(reglages => { if (actif) setEtat({ statut: "pret", reglages }); }).catch((e: unknown) => { if (actif) setEtat({ statut: "erreur", message: e instanceof Error ? e.message : "Les réglages locaux n’ont pas pu être chargés." }); }); return () => { actif = false; }; }, [tentative, utilisateur]);
  if (etat.statut === "chargement") return <section className="page-carte etat-tableau"><p>Chargement des réglages locaux autorisés par Grist…</p></section>;
  if (etat.statut === "erreur") return <section className="page-carte etat-tableau"><p>{etat.message}</p><button type="button" onClick={() => setTentative(v => v + 1)}>Réessayer</button></section>;
  const basculer = async (reglage: ReglagePerimetre) => { setEnregistrement(reglage.id); setMessage(null); try { await enregistrerReglage(reglage, !reglage.actif, utilisateur); setMessage({ type: "succes", texte: "Le réglage local a été enregistré." }); setTentative(v => v + 1); } catch (e) { setMessage({ type: "erreur", texte: e instanceof Error ? e.message : "Le réglage n’a pas pu être enregistré." }); } finally { setEnregistrement(null); } };
  return <section className="page-carte" aria-labelledby="titre-parametrage"><div className="entete-module"><div><p className="surtitre">Réglages locaux</p><h2 id="titre-parametrage">Paramétrage des indicateurs</h2><p>Activez ou désactivez les indicateurs applicables dans vos périmètres supervisés. Le référentiel central reste administré séparément.</p></div></div>{message && <p className={`message-formulaire message-${message.type}`} role="status">{message.texte}</p>}{etat.reglages.length ? <div className="liste-suivi">{etat.reglages.map(reglage => <article key={reglage.id}><div><strong>{reglage.codeIndicateur} · {reglage.indicateur}</strong><span>{reglage.perimetre}</span></div><button type="button" className="bouton-secondaire" onClick={() => basculer(reglage)} disabled={enregistrement !== null}>{enregistrement === reglage.id ? "Enregistrement…" : reglage.actif ? "Désactiver" : "Activer"}</button></article>)}</div> : <p className="aucun-suivi">Aucun réglage local accessible dans vos périmètres.</p>}</section>;
}
