import React, { FormEvent, useEffect, useState } from "react";
import { AxeReferentiel, CampagneReferentiel, chargerDonneesReferentiel, CritereReferentiel, DonneesReferentiel, enregistrerAxe, enregistrerCampagne, enregistrerCritere, enregistrerIndicateur, IndicateurReferentiel, NiveauCritere, SaisieAxe, SaisieCampagne, SaisieCritere, SaisieIndicateur, StatutCampagne } from "./reference-data.js";

type Onglet = "AXES" | "INDICATEURS" | "CRITERES" | "CAMPAGNES";
type Panneau = {type:"AXE";valeur:SaisieAxe}|{type:"INDICATEUR";valeur:SaisieIndicateur}|{type:"CRITERE";valeur:SaisieCritere}|{type:"CAMPAGNE";valeur:SaisieCampagne};
type Etat = {statut:"chargement"}|{statut:"erreur";message:string}|{statut:"pret";donnees:DonneesReferentiel};
const libellesOnglets:Record<Onglet,string>={AXES:"Axes",INDICATEURS:"Indicateurs",CRITERES:"Critères",CAMPAGNES:"Campagnes"};

export function ModuleReferentiel(){
  const [etat,setEtat]=useState<Etat>({statut:"chargement"}); const [tentative,setTentative]=useState(0); const [onglet,setOnglet]=useState<Onglet>("AXES");
  const [recherche,setRecherche]=useState(""); const [statut,setStatut]=useState("ACTIFS"); const [liaison,setLiaison]=useState(0); const [panneau,setPanneau]=useState<Panneau|null>(null); const [enregistrement,setEnregistrement]=useState(false); const [message,setMessage]=useState<{type:"succes"|"erreur";texte:string}|null>(null);
  useEffect(()=>{let actif=true;setEtat({statut:"chargement"});chargerDonneesReferentiel().then(d=>{if(actif)setEtat({statut:"pret",donnees:d});}).catch((e:unknown)=>{if(actif)setEtat({statut:"erreur",message:e instanceof Error?e.message:"Le référentiel n’a pas pu être chargé."});});return()=>{actif=false;};},[tentative]);
  if(etat.statut==="chargement")return <EtatReferentiel texte="Chargement du référentiel autorisé par Grist…"/>; if(etat.statut==="erreur")return <EtatReferentiel texte={etat.message} action={()=>setTentative(v=>v+1)}/>;
  const d=etat.donnees; const q=recherche.trim().toLowerCase(); const actif=(v:boolean)=>statut==="TOUS"||(statut==="ACTIFS"?v:!v);
  const axes=d.axes.filter(x=>actif(x.actif)&&(!q||`${x.code} ${x.titre} ${x.description}`.toLowerCase().includes(q)));
  const indicateurs=d.indicateurs.filter(x=>actif(x.actif)&&(!liaison||x.axeId===liaison)&&(!q||`${x.code} ${x.titre} ${x.axe}`.toLowerCase().includes(q)));
  const criteres=d.criteres.filter(x=>actif(x.actif)&&(!liaison||x.indicateurId===liaison)&&(!q||`${x.codeIndicateur} ${x.indicateur} ${x.libelle} ${x.niveau}`.toLowerCase().includes(q)));
  const campagnes=d.campagnes.filter(x=>(statut==="TOUS"||(statut==="ACTIFS"?["BROUILLON","OUVERTE"].includes(x.statut):["CLOTUREE","ARCHIVEE"].includes(x.statut)))&&(!liaison||x.perimetreId===liaison)&&(!q||`${x.code} ${x.titre} ${x.perimetre}`.toLowerCase().includes(q)));
  const ouvrir=()=>{setMessage(null);if(onglet==="AXES")setPanneau({type:"AXE",valeur:{code:`AXE_${d.axes.length+1}`,ordre:d.axes.length+1,titre:"",description:"",actif:true}});if(onglet==="INDICATEURS")setPanneau({type:"INDICATEUR",valeur:{code:`IND_${String(d.indicateurs.length+1).padStart(2,"0")}`,axeId:liaison||d.axes.find(x=>x.actif)?.id||0,ordre:d.indicateurs.length+1,titre:"",description:"",obligatoire:true,actif:true}});if(onglet==="CRITERES"){const indicateurId=liaison||d.indicateurs.find(x=>x.actif)?.id||0;const ordre=Math.max(0,...d.criteres.filter(x=>x.indicateurId===indicateurId&&x.niveau==="ROUGE").map(x=>x.ordre))+1;setPanneau({type:"CRITERE",valeur:{indicateurId,niveau:"ROUGE",ordre,libelle:"",actif:true}});}if(onglet==="CAMPAGNES")setPanneau({type:"CAMPAGNE",valeur:{code:`CAMP_${new Date().getFullYear()}_`,titre:"",perimetreId:liaison,dateDebut:aujourdhui(),dateFin:"",statut:"BROUILLON"}});};
  const soumettre=async(e:FormEvent)=>{e.preventDefault();if(!panneau)return;setEnregistrement(true);setMessage(null);try{if(panneau.type==="AXE")await enregistrerAxe(panneau.valeur,d);if(panneau.type==="INDICATEUR")await enregistrerIndicateur(panneau.valeur,d);if(panneau.type==="CRITERE")await enregistrerCritere(panneau.valeur,d);if(panneau.type==="CAMPAGNE")await enregistrerCampagne(panneau.valeur,d);setMessage({type:"succes",texte:"La fiche du référentiel a été enregistrée."});setPanneau(null);setTentative(v=>v+1);}catch(erreur){setMessage({type:"erreur",texte:erreur instanceof Error?erreur.message:"L’enregistrement a échoué."});}finally{setEnregistrement(false);}};
  const changerOnglet=(o:Onglet)=>{setOnglet(o);setPanneau(null);setLiaison(0);setStatut("ACTIFS");setRecherche("");};
  return <section className="page-carte module-referentiel" aria-labelledby="titre-referentiel"><div className="entete-module"><div><p className="surtitre">Référentiel central</p><h2 id="titre-referentiel">Axes, indicateurs, critères et campagnes</h2><p>Gérez les contenus du questionnaire et les périodes d’évaluation. Les données historiques restent protégées.</p></div><button type="button" onClick={ouvrir}>Ajouter {onglet==="AXES"?"un axe":onglet==="INDICATEURS"?"un indicateur":onglet==="CRITERES"?"un critère":"une campagne"}</button></div>
    <div className="synthese-referentiel"><Indicateur valeur={d.axes.filter(x=>x.actif).length} libelle="Axes actifs"/><Indicateur valeur={d.indicateurs.filter(x=>x.actif).length} libelle="Indicateurs actifs"/><Indicateur valeur={d.criteres.filter(x=>x.actif).length} libelle="Critères actifs"/><Indicateur valeur={d.campagnes.filter(x=>x.statut==="OUVERTE").length} libelle="Campagnes ouvertes"/></div>
    {message&&<p className={`message-formulaire message-${message.type}`} role="status">{message.texte}</p>}
    <div className="onglets-referentiel" role="tablist" aria-label="Tables du référentiel">{(Object.keys(libellesOnglets) as Onglet[]).map(o=><button type="button" role="tab" aria-selected={onglet===o} className={onglet===o?"onglet-actif":""} onClick={()=>changerOnglet(o)} key={o}>{libellesOnglets[o]} <span>{o==="AXES"?d.axes.length:o==="INDICATEURS"?d.indicateurs.length:o==="CRITERES"?d.criteres.length:d.campagnes.length}</span></button>)}</div>
    <Filtres onglet={onglet} recherche={recherche} setRecherche={setRecherche} statut={statut} setStatut={setStatut} liaison={liaison} setLiaison={setLiaison} d={d}/>
    <div className={panneau?"corps-referentiel avec-formulaire":"corps-referentiel"}><div className="liste-referentiel">{onglet==="AXES"&&axes.map(x=><CarteAxe x={x} modifier={()=>setPanneau({type:"AXE",valeur:{id:x.id,code:x.code,ordre:x.ordre,titre:x.titre,description:x.description,actif:x.actif}})} voir={()=>{changerOnglet("INDICATEURS");setLiaison(x.id);}} key={x.id}/>)}{onglet==="INDICATEURS"&&indicateurs.map(x=><CarteIndicateur x={x} modifier={()=>setPanneau({type:"INDICATEUR",valeur:{id:x.id,code:x.code,axeId:x.axeId,ordre:x.ordre,titre:x.titre,description:x.description,obligatoire:x.obligatoire,actif:x.actif}})} voir={()=>{changerOnglet("CRITERES");setLiaison(x.id);}} key={x.id}/>)}{onglet==="CRITERES"&&criteres.map(x=><CarteCritere x={x} modifier={()=>setPanneau({type:"CRITERE",valeur:{id:x.id,indicateurId:x.indicateurId,niveau:x.niveau,ordre:x.ordre,libelle:x.libelle,actif:x.actif}})} key={x.id}/>)}{onglet==="CAMPAGNES"&&campagnes.map(x=><CarteCampagne x={x} modifier={()=>setPanneau({type:"CAMPAGNE",valeur:{id:x.id,code:x.code,titre:x.titre,perimetreId:x.perimetreId||0,dateDebut:dateInput(x.dateDebutValeur),dateFin:dateInput(x.dateFinValeur),statut:x.statut}})} key={x.id}/>)}{!nombreVisible(onglet,axes,indicateurs,criteres,campagnes)&&<p className="aucun-suivi">Aucune ligne ne correspond aux filtres sélectionnés.</p>}</div>{panneau&&<Formulaire panneau={panneau} setPanneau={setPanneau} d={d} soumettre={soumettre} fermer={()=>setPanneau(null)} enregistrement={enregistrement}/>}</div>
  </section>;
}

function Indicateur({valeur,libelle}:{valeur:number;libelle:string}){return <div><strong>{valeur}</strong><span>{libelle}</span></div>}
function Filtres({onglet,recherche,setRecherche,statut,setStatut,liaison,setLiaison,d}:{onglet:Onglet;recherche:string;setRecherche:(v:string)=>void;statut:string;setStatut:(v:string)=>void;liaison:number;setLiaison:(v:number)=>void;d:DonneesReferentiel}){return <div className="filtres-referentiel"><label>Rechercher<input type="search" value={recherche} onChange={e=>setRecherche(e.target.value)} placeholder="Code, titre ou libellé"/></label>{onglet==="INDICATEURS"&&<label>Axe<select value={liaison} onChange={e=>setLiaison(Number(e.target.value))}><option value={0}>Tous</option>{d.axes.map(x=><option value={x.id} key={x.id}>{x.titre}</option>)}</select></label>}{onglet==="CRITERES"&&<label>Indicateur<select value={liaison} onChange={e=>setLiaison(Number(e.target.value))}><option value={0}>Tous</option>{d.indicateurs.map(x=><option value={x.id} key={x.id}>{x.code} · {x.titre}</option>)}</select></label>}{onglet==="CAMPAGNES"&&<label>Périmètre<select value={liaison} onChange={e=>setLiaison(Number(e.target.value))}><option value={0}>Tous les périmètres</option>{d.perimetres.map(x=><option value={x.id} key={x.id}>{x.nom}</option>)}</select></label>}<label>Statut<select value={statut} onChange={e=>setStatut(e.target.value)}><option value="ACTIFS">{onglet==="CAMPAGNES"?"En cours":"Actifs"}</option><option value="INACTIFS">{onglet==="CAMPAGNES"?"Terminées":"Inactifs"}</option><option value="TOUS">Tous</option></select></label></div>}
function Badge({actif}:{actif:boolean}){return <span className={actif?"badge-statut statut-actif":"badge-statut statut-inactif"}>{actif?"Actif":"Inactif"}</span>}
function CarteAxe({x,modifier,voir}:{x:AxeReferentiel;modifier:()=>void;voir:()=>void}){return <article className="carte-reference"><div className="titre-reference"><div><code>{x.code}</code><h3>{x.titre}</h3></div><Badge actif={x.actif}/></div><p>{x.description||"Aucune description."}</p><small>Ordre {x.ordre} · {x.indicateurs} indicateur(s)</small><div><button className="bouton-secondaire" onClick={voir}>Voir les indicateurs</button><button className="bouton-secondaire" onClick={modifier}>Modifier</button></div></article>}
function CarteIndicateur({x,modifier,voir}:{x:IndicateurReferentiel;modifier:()=>void;voir:()=>void}){return <article className="carte-reference"><div className="titre-reference"><div><code>{x.code}</code><h3>{x.titre}</h3></div><Badge actif={x.actif}/></div><p>{x.axe} · Ordre {x.ordre}</p><small>{x.criteres} critère(s) · {x.reponses} réponse(s){x.obligatoire?" · Obligatoire":""}</small><div><button className="bouton-secondaire" onClick={voir}>Voir les critères</button><button className="bouton-secondaire" onClick={modifier}>Modifier</button></div></article>}
function CarteCritere({x,modifier}:{x:CritereReferentiel;modifier:()=>void}){return <article className="carte-reference"><div className="titre-reference"><div><code>{x.codeIndicateur} · {x.niveau}</code><h3>{x.libelle}</h3></div><Badge actif={x.actif}/></div><small>{x.indicateur} · Ordre {x.ordre}</small><div><button className="bouton-secondaire" onClick={modifier}>Modifier</button></div></article>}
function CarteCampagne({x,modifier}:{x:CampagneReferentiel;modifier:()=>void}){return <article className="carte-reference"><div className="titre-reference"><div><code>{x.code}</code><h3>{x.titre}</h3></div><span className={`badge-campagne campagne-${x.statut.toLowerCase()}`}>{x.statut}</span></div><p>{x.perimetre}</p><small>{x.dateDebut} → {x.dateFin} · {x.evaluations} évaluation(s)</small><div><button className="bouton-secondaire" onClick={modifier}>Modifier / avancer</button></div></article>}

function Formulaire({panneau,setPanneau,d,soumettre,fermer,enregistrement}:{panneau:Panneau;setPanneau:(p:Panneau)=>void;d:DonneesReferentiel;soumettre:(e:FormEvent)=>void;fermer:()=>void;enregistrement:boolean}){const titre=panneau.type==="AXE"?"Axe":panneau.type==="INDICATEUR"?"Indicateur":panneau.type==="CRITERE"?"Critère":"Campagne";return <aside className="panneau-utilisateur panneau-reference" aria-labelledby="titre-form-reference"><div className="entete-panneau"><div><p className="surtitre">{panneau.valeur.id?"Modification":"Création"}</p><h3 id="titre-form-reference">{titre}</h3></div><button className="fermer-panneau" type="button" onClick={fermer} aria-label="Fermer le formulaire">×</button></div><form className="formulaire-utilisateur" onSubmit={soumettre}>{panneau.type==="AXE"&&<FormAxe v={panneau.valeur} change={v=>setPanneau({type:"AXE",valeur:v})}/>} {panneau.type==="INDICATEUR"&&<FormIndicateur v={panneau.valeur} change={v=>setPanneau({type:"INDICATEUR",valeur:v})} d={d}/>} {panneau.type==="CRITERE"&&<FormCritere v={panneau.valeur} change={v=>setPanneau({type:"CRITERE",valeur:v})} d={d}/>} {panneau.type==="CAMPAGNE"&&<FormCampagne v={panneau.valeur} change={v=>setPanneau({type:"CAMPAGNE",valeur:v})} d={d}/>}<div className="actions-formulaire"><button className="bouton-secondaire" type="button" onClick={fermer}>Annuler</button><button type="submit" disabled={enregistrement}>{enregistrement?"Enregistrement…":"Enregistrer"}</button></div></form></aside>}
function ChampCode({v,change,exemple}:{v:{id?:number;code:string};change:(code:string)=>void;exemple:string}){return <label>Code stable<input value={v.code} onChange={e=>change(e.target.value)} disabled={Boolean(v.id)} required/><small>{v.id?"Le code existant est immuable.":exemple}</small></label>}
function FormAxe({v,change}:{v:SaisieAxe;change:(v:SaisieAxe)=>void}){return <><ChampCode v={v} change={code=>change({...v,code})} exemple="Convention : AXE_1"/><label>Ordre<input type="number" min="1" value={v.ordre} onChange={e=>change({...v,ordre:Number(e.target.value)})}/></label><label>Titre<input value={v.titre} onChange={e=>change({...v,titre:e.target.value})} required/></label><label>Description<textarea value={v.description} onChange={e=>change({...v,description:e.target.value})}/></label><Case actif={v.actif} change={actif=>change({...v,actif})}/></>}
function FormIndicateur({v,change,d}:{v:SaisieIndicateur;change:(v:SaisieIndicateur)=>void;d:DonneesReferentiel}){return <><ChampCode v={v} change={code=>change({...v,code})} exemple="Convention : IND_01"/><label>Axe<select value={v.axeId} onChange={e=>change({...v,axeId:Number(e.target.value)})}>{d.axes.map(x=><option value={x.id} key={x.id}>{x.titre}</option>)}</select></label><label>Ordre<input type="number" min="1" value={v.ordre} onChange={e=>change({...v,ordre:Number(e.target.value)})}/></label><label>Titre<input value={v.titre} onChange={e=>change({...v,titre:e.target.value})} required/></label><label>Description<textarea value={v.description} onChange={e=>change({...v,description:e.target.value})}/></label><label className="ligne-case"><input type="checkbox" checked={v.obligatoire} onChange={e=>change({...v,obligatoire:e.target.checked})}/> Indicateur obligatoire</label><Case actif={v.actif} change={actif=>change({...v,actif})}/></>}
function FormCritere({v,change,d}:{v:SaisieCritere;change:(v:SaisieCritere)=>void;d:DonneesReferentiel}){return <><label>Indicateur<select value={v.indicateurId} onChange={e=>change({...v,indicateurId:Number(e.target.value)})}>{d.indicateurs.map(x=><option value={x.id} key={x.id}>{x.code} · {x.titre}</option>)}</select></label><label>Niveau<select value={v.niveau} onChange={e=>change({...v,niveau:e.target.value as NiveauCritere})}><option value="ROUGE">Rouge</option><option value="ORANGE">Orange</option><option value="VERT">Vert</option></select></label><label>Ordre<input type="number" min="1" value={v.ordre} onChange={e=>change({...v,ordre:Number(e.target.value)})}/></label><label>Libellé<textarea value={v.libelle} onChange={e=>change({...v,libelle:e.target.value})} required/></label><Case actif={v.actif} change={actif=>change({...v,actif})}/></>}
function FormCampagne({v,change,d}:{v:SaisieCampagne;change:(v:SaisieCampagne)=>void;d:DonneesReferentiel}){const existante=v.id?d.campagnes.find(x=>x.id===v.id):null;const ordre:StatutCampagne[]=["BROUILLON","OUVERTE","CLOTUREE","ARCHIVEE"];const autorises=existante?[existante.statut,ordre[ordre.indexOf(existante.statut)+1]].filter(Boolean) as StatutCampagne[]:["BROUILLON"] as StatutCampagne[];return <><ChampCode v={v} change={code=>change({...v,code})} exemple="Convention : CAMP_2026_S1"/><label>Titre<input value={v.titre} onChange={e=>change({...v,titre:e.target.value})} required/></label><label>Périmètre<select value={v.perimetreId} onChange={e=>change({...v,perimetreId:Number(e.target.value)})}><option value={0}>Campagne globale</option>{d.perimetres.map(x=><option value={x.id} key={x.id}>{x.nom}</option>)}</select></label><div className="deux-colonnes"><label>Début<input type="date" value={v.dateDebut} onChange={e=>change({...v,dateDebut:e.target.value})}/></label><label>Fin<input type="date" value={v.dateFin} onChange={e=>change({...v,dateFin:e.target.value})}/></label></div><label>Statut<select value={v.statut} onChange={e=>change({...v,statut:e.target.value as StatutCampagne})}>{autorises.map(x=><option value={x} key={x}>{x}</option>)}</select><small>Cycle : brouillon → ouverte → clôturée → archivée.</small></label></>}
function Case({actif,change}:{actif:boolean;change:(v:boolean)=>void}){return <label className="ligne-case"><input type="checkbox" checked={actif} onChange={e=>change(e.target.checked)}/> Référence active</label>}
function EtatReferentiel({texte,action}:{texte:string;action?:()=>void}){return <section className="page-carte etat-tableau"><p>{texte}</p>{action&&<button onClick={action}>Réessayer</button>}</section>}
function nombreVisible(o:Onglet,a:readonly unknown[],i:readonly unknown[],c:readonly unknown[],ca:readonly unknown[]){return o==="AXES"?a.length:o==="INDICATEURS"?i.length:o==="CRITERES"?c.length:ca.length}
function aujourdhui(){return new Date().toISOString().slice(0,10)} function dateInput(v:number|null){return v?new Date(v*1000).toISOString().slice(0,10):""}
