import { obtenirDocApiGrist, TableGrist } from "./grist-context.js";
import { UtilisateurCourant } from "./portal-data.js";

export interface ParametreApplication { id:number; cle:string; valeur:string; description:string; updatedAt:string; updatedBy:string; }

export async function chargerParametres():Promise<readonly ParametreApplication[]>{const api=obtenirDocApiGrist();if(!api)return construireParametres(demoParametres());return construireParametres(await api.fetchTable("Parametres"));}
export function construireParametres(table:TableGrist):ParametreApplication[]{return(table.id??[]).flatMap((v,i)=>{const id=nombre(v);if(!id)return[];return[{id,cle:texte(table.Cle?.[i]),valeur:texte(table.Valeur?.[i]),description:texte(table.Description?.[i]),updatedAt:dateHeure(table.UpdatedAt?.[i]),updatedBy:texte(table.UpdatedByEmail?.[i])||"—"}];}).sort((a,b)=>a.cle.localeCompare(b.cle,"fr"));}
export async function enregistrerParametre(p:ParametreApplication,valeur:string,description:string,u:UtilisateurCourant):Promise<void>{const api=obtenirDocApiGrist();if(!api)throw new Error("L’enregistrement est disponible uniquement depuis le widget Grist.");if(contientSecret(p.cle,description))throw new Error("Les paramètres ne doivent contenir ni secret, ni mot de passe, ni jeton d’accès.");await api.applyUserActions([["UpdateRecord","Parametres",p.id,{Valeur:valeur.trim(),Description:description.trim()}],["AddRecord","JournalAudit",null,{Uid:crypto.randomUUID(),Acteur:u.id,TypeObjet:"PARAMETRE",ObjetUid:p.cle,Action:"MODIFICATION",Resume:`Paramètre ${p.cle} mis à jour`}]]);}
export function validerValeur(cle:string,valeur:string):string|null{const v=valeur.trim();if(!v)return"La valeur ne peut pas être vide.";if(cle==="PDF_MAX_SIZE_MB"&&(!/^\d+$/.test(v)||Number(v)<1||Number(v)>50))return"La taille PDF doit être comprise entre 1 et 50 Mo.";if(cle==="APP_LOCALE"&&!/^[a-z]{2}-[A-Z]{2}$/.test(v))return"Le format attendu est de type fr-FR.";if(cle==="APP_TIMEZONE"&&!v.includes("/"))return"Utilisez un fuseau de type Europe/Paris.";if(cle==="SCHEMA_VERSION"&&!/^\d+\.\d+\.\d+$/.test(v))return"La version du schéma doit respecter le format 1.0.0.";return null;}
function contientSecret(cle:string,description:string):boolean{return/(PASSWORD|SECRET|TOKEN|API[_ -]?KEY|MOT DE PASSE|JETON)/i.test(`${cle} ${description}`);}function demoParametres():TableGrist{return{id:[1,2,3,4,5],Cle:["APP_NAME","APP_LOCALE","APP_TIMEZONE","PDF_MAX_SIZE_MB","SCHEMA_VERSION"],Valeur:["Auto-évaluation des pratiques de recrutement SPV","fr-FR","Europe/Paris","10","1.0.0"],Description:["Nom affiché de l’application","Paramètres régionaux de l’interface","Fuseau horaire fonctionnel","Taille maximale autorisée pour un PDF, en mégaoctets","Version du schéma Grist installé"],UpdatedAt:[1_700_000_000,1_700_000_000,1_700_000_000,1_700_000_000,1_700_000_000],UpdatedByEmail:Array(5).fill("admin@example.invalid")};}function dateHeure(v:unknown):string{const n=nombre(v);return n?new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(n*1000)):"—";}function nombre(v:unknown):number|null{return typeof v==="number"&&Number.isFinite(v)?v:null;}function texte(v:unknown):string{return typeof v==="string"?v:"";}
