import React, { FormEvent, useEffect, useState } from "react";
import { UtilisateurCourant } from "./portal-data.js";
import { ajouterVersion, archiverFiche, chargerDonneesPedagogiques, DonneesPedagogiques, enregistrerFiche, enregistrerLiaison, FichePedagogique, LiaisonPedagogique, publierVersion, SaisieFiche, SaisieLiaison, SaisieVersion, urlVersion, VersionPedagogique } from "./teaching-data.js";

type Etat={statut:"chargement"}|{statut:"erreur";message:string}|{statut:"pret";donnees:DonneesPedagogiques};
type Panneau={type:"FICHE";valeur:SaisieFiche}|{type:"VERSION";valeur:SaisieVersion}|{type:"LIAISON";valeur:SaisieLiaison};

export function ModulePedagogique({utilisateur}:{utilisateur:UtilisateurCourant}){
  const[etat,setEtat]=useState<Etat>({statut:"chargement"});const[tentative,setTentative]=useState(0);const[selection,setSelection]=useState<number|null>(null);const[panneau,setPanneau]=useState<Panneau|null>(null);const[recherche,setRecherche]=useState("");const[statut,setStatut]=useState("ACTIVES");const[enregistrement,setEnregistrement]=useState(false);const[operation,setOperation]=useState<string|null>(null);const[message,setMessage]=useState<{type:"succes"|"erreur";texte:string}|null>(null);
  useEffect(()=>{let actif=true;setEtat({statut:"chargement"});chargerDonneesPedagogiques().then(d=>{if(actif){setEtat({statut:"pret",donnees:d});setSelection(id=>id&&d.fiches.some(f=>f.id===id)?id:d.fiches[0]?.id??null);}}).catch((e:unknown)=>{if(actif)setEtat({statut:"erreur",message:e instanceof Error?e.message:"Les fiches pédagogiques n’ont pas pu être chargées."});});return()=>{actif=false};},[tentative]);
  if(etat.statut==="chargement")return <EtatPedagogique texte="Chargement des ressources pédagogiques autorisées par Grist…"/>;if(etat.statut==="erreur")return <EtatPedagogique texte={etat.message} action={()=>setTentative(v=>v+1)}/>;
  const d=etat.donnees;const q=recherche.trim().toLocaleLowerCase("fr");const fiches=d.fiches.filter(f=>(statut==="TOUTES"||(statut==="ACTIVES"?f.statut!=="ARCHIVEE":f.statut==="ARCHIVEE"))&&(!q||`${f.code} ${f.titre} ${f.description} ${f.perimetre}`.toLocaleLowerCase("fr").includes(q)));const fiche=d.fiches.find(f=>f.id===selection)||null;
  const recharger=(texte:string)=>{setMessage({type:"succes",texte});setPanneau(null);setTentative(v=>v+1)};const erreur=(e:unknown)=>setMessage({type:"erreur",texte:e instanceof Error?e.message:"L’opération a échoué."});
  const soumettre=async(e:FormEvent)=>{e.preventDefault();if(!panneau)return;setEnregistrement(true);setMessage(null);try{if(panneau.type==="FICHE")await enregistrerFiche(panneau.valeur,d,utilisateur.id);if(panneau.type==="VERSION")await ajouterVersion(panneau.valeur,d,utilisateur.id);if(panneau.type==="LIAISON")await enregistrerLiaison(panneau.valeur,d);recharger(panneau.type==="VERSION"?"Le PDF a été déposé et sa version historisée.":"Les informations pédagogiques ont été enregistrées.");}catch(e){erreur(e)}finally{setEnregistrement(false)}};
  const publier=async(v:VersionPedagogique)=>{if(!fiche)return;setOperation(`pub-${v.id}`);setMessage(null);try{await publierVersion(fiche.id,v.id,d);recharger(`La version ${v.numero} est maintenant la version active.`)}catch(e){erreur(e)}finally{setOperation(null)}};
  const archiver=async()=>{if(!fiche)return;setOperation("archive");setMessage(null);try{await archiverFiche(fiche.id,d);recharger("La fiche a été archivée sans supprimer son historique.")}catch(e){erreur(e)}finally{setOperation(null)}};
  const telecharger=async(v:VersionPedagogique)=>{setOperation(`dl-${v.id}`);try{const url=await urlVersion(v);const lien=document.createElement("a");lien.href=url;lien.download=v.nomFichier||`${fiche?.code}-${v.numero}.pdf`;lien.rel="noopener";lien.click()}catch(e){erreur(e)}finally{setOperation(null)}};
  const nouvelle=()=>setPanneau({type:"FICHE",valeur:{code:`FICHE_${String(d.fiches.length+1).padStart(2,"0")}`,titre:"",description:"",perimetreId:0,actif:true}});
  return <section className="page-carte module-pedagogique" aria-labelledby="titre-pedagogie"><div className="entete-module"><div><p className="surtitre">Ressources et remédiation</p><h2 id="titre-pedagogie">Fiches pédagogiques</h2><p>Créez les fiches, associez-les aux indicateurs puis publiez des versions PDF immuables dans Grist.</p></div><button type="button" onClick={nouvelle}>Nouvelle fiche</button></div>
    <div className="synthese-pedagogie"><Indicateur valeur={d.fiches.filter(f=>f.statut==="PUBLIEE"&&f.actif).length} libelle="Fiches publiées"/><Indicateur valeur={d.fiches.filter(f=>f.statut==="BROUILLON").length} libelle="Brouillons"/><Indicateur valeur={d.versions.filter(v=>v.estPubliee).length} libelle="Versions publiées"/><Indicateur valeur={d.liaisons.filter(l=>l.actif).length} libelle="Liaisons actives"/></div>
    {message&&<p className={`message-formulaire message-${message.type}`} role="status">{message.texte}</p>}
    <div className="filtres-pedagogie"><label>Rechercher<input type="search" value={recherche} onChange={e=>setRecherche(e.target.value)} placeholder="Code, titre ou périmètre"/></label><label>Statut<select value={statut} onChange={e=>setStatut(e.target.value)}><option value="ACTIVES">Actives et brouillons</option><option value="ARCHIVEES">Archivées</option><option value="TOUTES">Toutes</option></select></label></div>
    <div className={panneau?"corps-pedagogie avec-formulaire":"corps-pedagogie"}><div className="colonne-fiches"><ListeFiches fiches={fiches} selection={selection} choisir={id=>{setSelection(id);setPanneau(null)}}/>{fiche&&<DetailFiche fiche={fiche} d={d} utilisateur={utilisateur} modifier={()=>setPanneau({type:"FICHE",valeur:{id:fiche.id,code:fiche.code,titre:fiche.titre,description:fiche.description,perimetreId:fiche.perimetreId||0,actif:fiche.actif}})} ajouterVersion={()=>setPanneau({type:"VERSION",valeur:{ficheId:fiche.id,numero:prochaineVersion(fiche,d),dateFin:"",fichier:null}})} ajouterLiaison={()=>setPanneau({type:"LIAISON",valeur:{ficheId:fiche.id,indicateurId:d.indicateurs.find(i=>i.actif&&!d.liaisons.some(l=>l.ficheId===fiche.id&&l.indicateurId===i.id))?.id||0,rouge:true,orange:true,actif:true}})} modifierLiaison={l=>setPanneau({type:"LIAISON",valeur:{id:l.id,ficheId:l.ficheId,indicateurId:l.indicateurId,rouge:l.rouge,orange:l.orange,actif:l.actif}})} publier={publier} archiver={archiver} telecharger={telecharger} operation={operation}/>}</div>{panneau&&<Formulaire panneau={panneau} setPanneau={setPanneau} d={d} fermer={()=>setPanneau(null)} soumettre={soumettre} enregistrement={enregistrement}/>}</div>
  </section>;
}

function Indicateur({valeur,libelle}:{valeur:number;libelle:string}){return <div><strong>{valeur}</strong><span>{libelle}</span></div>}
function ListeFiches({fiches,selection,choisir}:{fiches:readonly FichePedagogique[];selection:number|null;choisir:(id:number)=>void}){if(!fiches.length)return <p className="aucun-suivi">Aucune fiche ne correspond aux filtres.</p>;return <div className="liste-fiches">{fiches.map(f=><button type="button" className={selection===f.id?"carte-fiche fiche-selectionnee":"carte-fiche"} onClick={()=>choisir(f.id)} key={f.id}><span><code>{f.code}</code><strong>{f.titre}</strong><small>{f.perimetre}</small></span><span className={`badge-fiche fiche-${f.statut.toLowerCase()}`}>{f.statut}</span></button>)}</div>}
function DetailFiche({fiche,d,utilisateur,modifier,ajouterVersion,ajouterLiaison,modifierLiaison,publier,archiver,telecharger,operation}:{fiche:FichePedagogique;d:DonneesPedagogiques;utilisateur:UtilisateurCourant;modifier:()=>void;ajouterVersion:()=>void;ajouterLiaison:()=>void;modifierLiaison:(l:LiaisonPedagogique)=>void;publier:(v:VersionPedagogique)=>void;archiver:()=>void;telecharger:(v:VersionPedagogique)=>void;operation:string|null}){const versions=d.versions.filter(v=>v.ficheId===fiche.id),liaisons=d.liaisons.filter(l=>l.ficheId===fiche.id);const creationLiaison=utilisateur.role==="ADMIN"||fiche.statut==="BROUILLON";return <article className="detail-fiche"><div className="entete-detail-fiche"><div><p className="surtitre">{fiche.code}</p><h3>{fiche.titre}</h3><p>{fiche.description||"Aucune description."}</p></div><span className={`badge-fiche fiche-${fiche.statut.toLowerCase()}`}>{fiche.statut}</span></div><dl><div><dt>Périmètre</dt><dd>{fiche.perimetre}</dd></div><div><dt>Version active</dt><dd>{fiche.versionActive}</dd></div></dl>{fiche.statut!=="ARCHIVEE"&&<div className="actions-fiche"><button type="button" className="bouton-secondaire" onClick={modifier}>Modifier</button><button type="button" onClick={ajouterVersion}>Ajouter un PDF</button>{creationLiaison&&<button type="button" className="bouton-secondaire" onClick={ajouterLiaison}>Lier un indicateur</button>}{fiche.statut==="PUBLIEE"&&<button type="button" className="bouton-danger" onClick={archiver} disabled={operation!==null}>{operation==="archive"?"Archivage…":"Archiver"}</button>}</div>}
  <section className="bloc-fiche"><h4>Versions PDF</h4>{versions.length?<div className="liste-versions">{versions.map(v=><div key={v.id}><span><strong>Version {v.numero}</strong><small>{v.nomFichier} · {taille(v.taille)} · {v.auteur}</small></span><span className={v.estPubliee?"badge-statut statut-actif":"badge-statut statut-inactif"}>{v.estPubliee?"Publiée":"Brouillon"}</span><button type="button" className="bouton-secondaire" onClick={()=>telecharger(v)} disabled={operation!==null}>{operation===`dl-${v.id}`?"Ouverture…":"Ouvrir"}</button>{!v.estPubliee&&<button type="button" onClick={()=>publier(v)} disabled={operation!==null}>{operation===`pub-${v.id}`?"Publication…":"Publier"}</button>}</div>)}</div>:<p className="aucun-suivi">Aucune version PDF.</p>}</section>
  <section className="bloc-fiche"><h4>Déclenchement par indicateur</h4>{liaisons.length?<div className="liste-liaisons">{liaisons.map(l=><button type="button" className="liaison-fiche" onClick={()=>modifierLiaison(l)} key={l.id}><span><code>{l.codeIndicateur}</code><strong>{l.indicateur}</strong></span><span>{l.rouge?"Rouge ":""}{l.orange?"Orange":""}{!l.actif?" · inactive":""}</span></button>)}</div>:<p className="aucun-suivi">Aucun indicateur lié.</p>}</section></article>}

function Formulaire({panneau,setPanneau,d,fermer,soumettre,enregistrement}:{panneau:Panneau;setPanneau:(p:Panneau)=>void;d:DonneesPedagogiques;fermer:()=>void;soumettre:(e:FormEvent)=>void;enregistrement:boolean}){const titre=panneau.type==="FICHE"?"Fiche pédagogique":panneau.type==="VERSION"?"Nouvelle version PDF":"Liaison indicateur";const modification=panneau.type!=="VERSION"&&Boolean(panneau.valeur.id);return <aside className="panneau-utilisateur panneau-pedagogique" aria-labelledby="titre-form-pedagogie"><div className="entete-panneau"><div><p className="surtitre">{modification?"Modification":"Création"}</p><h3 id="titre-form-pedagogie">{titre}</h3></div><button type="button" className="fermer-panneau" onClick={fermer} aria-label="Fermer">×</button></div><form className="formulaire-utilisateur" onSubmit={soumettre}>{panneau.type==="FICHE"&&<FormFiche v={panneau.valeur} change={v=>setPanneau({type:"FICHE",valeur:v})} d={d}/>} {panneau.type==="VERSION"&&<FormVersion v={panneau.valeur} change={v=>setPanneau({type:"VERSION",valeur:v})}/>} {panneau.type==="LIAISON"&&<FormLiaison v={panneau.valeur} change={v=>setPanneau({type:"LIAISON",valeur:v})} d={d}/>}<div className="actions-formulaire"><button type="button" className="bouton-secondaire" onClick={fermer}>Annuler</button><button type="submit" disabled={enregistrement}>{enregistrement?"Enregistrement…":"Enregistrer"}</button></div></form></aside>}
function FormFiche({v,change,d}:{v:SaisieFiche;change:(v:SaisieFiche)=>void;d:DonneesPedagogiques}){return <><label>Code stable<input value={v.code} onChange={e=>change({...v,code:e.target.value})} disabled={Boolean(v.id)} required/><small>Convention : FICHE_IND_01</small></label><label>Titre<input value={v.titre} onChange={e=>change({...v,titre:e.target.value})} required/></label><label>Description<textarea value={v.description} onChange={e=>change({...v,description:e.target.value})}/></label><label>Périmètre<select value={v.perimetreId} onChange={e=>change({...v,perimetreId:Number(e.target.value)})}><option value={0}>Nationale / globale</option>{d.perimetres.filter(p=>p.actif).map(p=><option value={p.id} key={p.id}>{p.nom}</option>)}</select></label><label className="ligne-case"><input type="checkbox" checked={v.actif} onChange={e=>change({...v,actif:e.target.checked})}/> Fiche active</label></>}
function FormVersion({v,change}:{v:SaisieVersion;change:(v:SaisieVersion)=>void}){return <><label>Numéro de version<input value={v.numero} onChange={e=>change({...v,numero:e.target.value})} placeholder="1.0" required/></label><label>Fichier PDF<input className="champ-fichier" type="file" accept="application/pdf,.pdf" onChange={e=>change({...v,fichier:e.target.files?.[0]||null})} required/><small>Un seul PDF, 10 Mo maximum.</small></label><label>Fin de validité facultative<input type="date" value={v.dateFin} onChange={e=>change({...v,dateFin:e.target.value})}/></label><div className="encart-information"><strong>Version immuable après publication</strong><p>Une correction ultérieure nécessitera une nouvelle version.</p></div></>}
function FormLiaison({v,change,d}:{v:SaisieLiaison;change:(v:SaisieLiaison)=>void;d:DonneesPedagogiques}){return <><label>Indicateur<select value={v.indicateurId} onChange={e=>change({...v,indicateurId:Number(e.target.value)})} disabled={Boolean(v.id)} required><option value={0}>Sélectionner…</option>{d.indicateurs.filter(i=>i.actif).map(i=><option value={i.id} key={i.id}>{i.nom}</option>)}</select></label><label className="ligne-case"><input type="checkbox" checked={v.rouge} onChange={e=>change({...v,rouge:e.target.checked})}/> Proposer pour un résultat rouge</label><label className="ligne-case"><input type="checkbox" checked={v.orange} onChange={e=>change({...v,orange:e.target.checked})}/> Proposer pour un résultat orange</label><label className="ligne-case"><input type="checkbox" checked={v.actif} onChange={e=>change({...v,actif:e.target.checked})}/> Liaison active</label></>}
function EtatPedagogique({texte,action}:{texte:string;action?:()=>void}){return <section className="page-carte etat-tableau" aria-live="polite"><p>{texte}</p>{action&&<button type="button" onClick={action}>Réessayer</button>}</section>}
function prochaineVersion(f:FichePedagogique,d:DonneesPedagogiques){const nums=d.versions.filter(v=>v.ficheId===f.id).map(v=>Number(v.numero)).filter(Number.isFinite);return nums.length?(Math.max(...nums)+.1).toFixed(1):"1.0"}function taille(o:number){return o>=1048576?`${(o/1048576).toFixed(1)} Mo`:`${Math.max(1,Math.round(o/1024))} Ko`}
